In [1]:
import pandas as pd
inpFilePath ='/Users/sam/git/Pandas_Data/Input/Data_2019/'
df = pd.read_csv(inpFilePath+'survey_results_public.csv')
schema_df = pd.read_csv(inpFilePath+'survey_results_schema.csv')
pd.set_option('display.max_columns', 85) #to display all columns in the dataframe
pd.set_option('display.max_rows', 85)   #to see all rows in the dataframe of schema
pd.set_option('max_colwidth', 100) #to see the 1000 chars column width of the dataframe of schema

In [2]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software is about the same,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or tool without taking a formal course",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a job board","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software is about the same,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",NaN,Taken an online course in programming or software development (e.g. a MOOC),NaN,"Developer, desktop or enterprise applications;Developer, front-end",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the company or organization;Specific department or te...,"Something else changed (education, award, media, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change many aspects of our lives,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Designer;Developer, back-end;Developer, front-end;Developer, full-stack",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new opportunities",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies I'd be working with;Remote work options;Flex time ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what seems most important or urgent,Distracting work environment;Inadequate access to necessary tools;Lack of support from management,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software is about the same,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job ...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Interview with people in senior / management roles",No,"Languages, frameworks, and other technologies I'd be working with;Office environment or company ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what seems most important or urgent,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence on purchasing new technology,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the time / relax,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job ...,"10,000 or more employees","Academic researcher;Developer, desktop or enterprise applications;Developer, full-stack;Develope...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a whiteboard);Solve a brain-teaser style puzzle;Inte...",No,"Industry that I'd be working in;Languages, frameworks, and other technologies I'd be working wit...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",Being tasked with non-development work;Inadequate access to necessary tools;Non-work commitments...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per year,The quality of OSS and closed source software is about the same,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or tool without taking a formal course;Contributed to...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change many aspects of our lives,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Pass the...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Overflow,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","No, not at all",NaN,Tech articles written by other developers;Tech meetups or events in your area;Courses on technol...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software is about the same,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than proprietary / closed source software","Independent contractor, freelancer, or self-employed",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than proprietary / closed source software","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Taken a part-time in...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript;PHP;SQL;Swift,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or Watson;iOS;Linux;MacOS;Slack;Windows,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++;Sublime Text,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Get a se...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European descent,No,Appropriate in length,Easy

In [3]:
people = {
    "first": ["Corey", "Jane", "John"],
    "last": ["Schafer", "Doe", "Smith"],
    "email": ["Corey.Schafer@gmail.com", "Jane.Doe@gmail.com", "John.Smith@gmail.com"]
}

In [4]:
df1 = pd.DataFrame(people)

In [5]:
df1

   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John    Smith     John.Smith@gmail.com

In [ ]:
df1.set_index('email') #email column is now index of the dataframe
#i.e. loc will now use email column to access the data instead of the default index (0,1,2)
#this function call will not change the original dataframe df1, 
# it will return a new dataframe with email as index. 
# To change the original dataframe we can use inplace=True
#df1.set_index('email', inplace=True)

                         first     last
email
Corey.Schafer@gmail.com  Corey  Schafer
Jane.Doe@gmail.com        Jane      Doe
John.Smith@gmail.com      John    Smith

In [9]:
df1.index

RangeIndex(start=0, stop=3, step=1)

In [10]:
df1

   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John    Smith     John.Smith@gmail.com

In [11]:
df1.set_index('email', inplace=True)
#This might be useful when email address as index 
# given nice unique indentifier  to search as row
#now email has become label for loc method to search for row

In [12]:
df1

                         first     last
email
Corey.Schafer@gmail.com  Corey  Schafer
Jane.Doe@gmail.com        Jane      Doe
John.Smith@gmail.com      John    Smith

In [ ]:
df1.index

Index(['Corey.Schafer@gmail.com', 'Jane.Doe@gmail.com',
       'John.Smith@gmail.com'],
      dtype='object', name='email')

In [14]:
df1.loc['Corey.Schafer@gmail.com']

first      Corey
last     Schafer
Name: Corey.Schafer@gmail.com, dtype: object

In [20]:
df1.loc['Corey.Schafer@gmail.com','last']

'Schafer'

In [19]:
#df1.loc[0] #this will give error as email is index and not number
'''
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2894             try:
-> 2895                 return self._engine.get_loc(casted_key)
   2896             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-17-b8b9d5afcc6b> in <module>
----> 1 df1.loc[0] #this will give error as email is index and not number

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py in __getitem__(self, key)
    877 
...
-> 2897                 raise KeyError(key) from err
   2898 
   2899         if tolerance is not No

'''

'\n---------------------------------------------------------------------------\nKeyError                                  Traceback (most recent call last)\n~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)\n   2894             try:\n-> 2895                 return self._engine.get_loc(casted_key)\n   2896             except KeyError as err:\n\npandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()\n\npandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()\n\npandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()\n\npandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()\n\nKeyError: 0\n\nThe above exception was the direct cause of the following exception:\n\nKeyError                                  Traceback (most recent call last)\n<ipython-input-17-b8b9d5afcc6b> in <module>\n----> 1 df1.loc[0] #this will give error as email is index and not number\n\n~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py in __getitem__(self, key)\n    877 \n...\n-> 2897                 raise KeyError(key) from err\n   2898 \n   2899         if tolerance is not No\n\n'

In [21]:
df1.iloc[0]

first      Corey
last     Schafer
Name: Corey.Schafer@gmail.com, dtype: object

In [22]:
df1.reset_index(inplace=True) #to reset the index to default number

In [23]:
df1 #email is now back as column and index is default number

                     email  first     last
0  Corey.Schafer@gmail.com  Corey  Schafer
1       Jane.Doe@gmail.com   Jane      Doe
2     John.Smith@gmail.com   John    Smith

In [24]:
df2 = pd.read_csv(inpFilePath+'survey_results_public.csv',index_col='Respondent') 
#this will set Respondent column as index of the dataframe
df2.head(5)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software is about the same,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or tool without taking a formal course",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a job board","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software is about the same,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",NaN,Taken an online course in programming or software development (e.g. a MOOC),NaN,"Developer, desktop or enterprise applications;Developer, front-end",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the company or organization;Specific department or te...,"Something else changed (education, award, media, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change many aspects of our lives,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Designer;Developer, back-end;Developer, front-end;Developer, full-stack",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new opportunities",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies I'd be working with;Remote work options;Flex time ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what seems most important or urgent,Distracting work environment;Inadequate access to necessary tools;Lack of support from management,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software is about the same,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job ...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Interview with people in senior / management roles",No,"Languages, frameworks, and other technologies I'd be working with;Office environment or company ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what seems most important or urgent,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence on purchasing new technology,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the time / relax,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job ...,"10,000 or more employees","Academic researcher;Developer, desktop or enterprise applications;Developer, full-stack;Develope...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a whiteboard);Solve a brain-teaser style puzzle;Inte...",No,"Industry that I'd be working in;Languages, frameworks, and other technologies I'd be working wit...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",Being tasked with non-development work;Inadequate access to necessary tools;Non-work commitments...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [25]:
df2.loc[1,'MainBranch':'Country'] 
#to access row with index label 1 which is Respondent number 1
#this is equivalent to df.iloc[0] as index starts from 0 in iloc and from 1 in loc for this dataframe

MainBranch                              I am a student who is learning to code
Hobbyist                                                                   Yes
OpenSourcer                                                              Never
OpenSource     The quality of OSS and closed source software is about the same
Employment                              Not employed, and not looking for work
Country                                                         United Kingdom
Name: 1, dtype: object

In [27]:
 
#df2.iloc[0,'MainBranch':'Country']
#this will give error as iloc only accepts integer position and not column labels

df2.iloc[0,0:6]

MainBranch                              I am a student who is learning to code
Hobbyist                                                                   Yes
OpenSourcer                                                              Never
OpenSource     The quality of OSS and closed source software is about the same
Employment                              Not employed, and not looking for work
Country                                                         United Kingdom
Name: 1, dtype: object

In [30]:
schema_df2 = pd.read_csv(inpFilePath+'survey_results_schema.csv',index_col='Column')

In [31]:
schema_df2

                                                                                                               QuestionText
Column
Respondent                                           Randomized respondent ID number (not in order of survey response time)
MainBranch              Which of the following options best describes you today? Here, by "developer" we mean "someone w...
Hobbyist                                                                                            Do you code as a hobby?
OpenSourcer                                                                     How often do you contribute to open source?
OpenSource                                                 How do you feel about the quality of open source software (OSS)?
Employment                                            Which of the following best describes your current employment status?
Country                                                                           In which country do you currently reside?
Student                              Are you currently enrolled in a formal, degree-granting college or university program?
EdLevel                  Which of the following best describes the highest level of formal education that you’ve completed?
UndergradMajor                                                         What was your main or most important field of study?
EduOther                Which of the following types of non-degree education have you used or participated in? Please se...
OrgSize                             Approximately how many people are employed by the company or organization you work for?
DevType                                                  Which of the following describe you? Please select all that apply.
YearsCode                                                     Including any education, how many years have you been coding?
Age1stCode              At what age did you write your first line of code or program? (E.g., webpage, Hello World, Scrat...
YearsCodePro                                         How many years have you coded professionally (as a part of your work)?
CareerSat                                                         Overall, how satisfied are you with your career thus far?
JobSat                  How satisfied are you with your current job? (If you work multiple jobs, answer for the one you ...
MgrIdiot                                                  How confident are you that your manager knows what they’re doing?
MgrMoney                                                   Do you believe that you need to be a manager to make more money?
MgrWant                                                             Do you want to become a manager yourself in the future?
JobSeek                                              Which of the following best describes your current job-seeking status?
LastHireDate                                                When was the last time that you took a job with a new employer?
LastInt                 In your most recent successful job interview (resulting in a job offer), you were asked to... (c...
FizzBuzz                                                        Have you ever been asked to solve FizzBuzz in an interview?
JobFactors              Imagine that you are deciding between two job offers with the same compensation, benefits, and l...
ResumeUpdate            Think back to the last time you updated your resumé, CV, or an online profile on a job site. Wha...
CurrencySymbol          Which currency do you use day-to-day? If your answer is complicated, please pick the one you're ...
CurrencyDesc            Which currency do you use day-to-day? If your answer is complicated, please pick the one you're ...
CompTotal               What is your current total compensation (salary, bonuses, and perks, before taxes and deductions...
CompFreq                                                                   Is that compensation weekly, monthly, or yearly?
ConvertedComp           Salary converted to annual USD salaries using the exchange rate on 2019-02-01, assuming 12 worki...
WorkWeekHrs                                                                On average, how many hours per week do you work?
WorkPlan                                                                            How structured or planned is your work?
WorkChallenge           Of these options, what are your greatest challenges to productivity as a developer? Select up to 3:
WorkRemote                                                                                  How often do you work remotely?
WorkLoc                                                                                     Where would you prefer to work?
ImpSyn                  For the specific work you do, and the years of experience you have, how do you rate your own lev...
CodeRev                                                                            Do you review code as part of your work?
CodeRevHrs                                                 On average, how many hours per week do you spend on code review?
UnitTests                               Does your company regularly employ unit tests in the development of their products?
PurchaseHow               How does your company make decisions about purchasing new technology (cloud, AI, IoT, databases)?
PurchaseWhat            What level of influence do you, personally, have over new technology purchases at your organizat...
LanguageWorkedWith      Which of the following programming, scripting, and markup languages have you done extensive deve...
LanguageDesireNextYear  Which of the following programming, scripting, and markup languages have you done extensive deve...
DatabaseWorkedWith      Which of the following database environments have you done extensive development work in over th...
DatabaseDesireNextYear  Which of the following database environments have you done extensive development work in over th...
PlatformWorkedWith      Which of the following platforms have you done extensive development work for over the past year...
PlatformDesireNextYear  Which of the following platforms have you done extensive development work for over the past year...
WebFrameWorkedWith      Which of the following web frameworks have you done extensive development work in over the past ...
WebFrameDesireNextYear  Which of the following web frameworks have you done extensive development work in over the past ...
MiscTechWorkedWith      Which of the following other frameworks, libraries, and tools have you done extensive developmen...
MiscTechDesireNextYear  Which of the following other frameworks, libraries, and tools have you done extensive developmen...
DevEnviron                             Which development environment(s) do you use regularly?  Please check all that apply.
OpSys                                                               What is the primary operating system in which you work?
Containers                                       How do you use containers (Docker, Open Container Initiative (OCI), etc.)?
BlockchainOrg                                How is your organization thinking about or implementing blockchain technology?
BlockchainIs                                                           Blockchain / cryptocurrency technology is primarily:
BetterLife                                       Do you think people born today will have a better life than their parents?
ITperson                                                                   Are you the "IT support person" for your family?
OffOn                                                                           Have you tried turning it off and on again?
SocialMedia                                                                     What social media site do you use the most?
Extraversion                                                                Do you prefer online chat or IRL conversations?
ScreenName                                                                                             What do you call it?
SOVisit1st                                             To the best of your memory, when did you first visit Stack Overflow?
SOVisitFreq                                                          How frequently would you say you visit Stack Overflow?
SOVisitTo                                                               I visit Stack Overflow to... (check all that apply)
SOFindAnswer                           On average, how many times a week do you find (and use) an answer on Stack Overflow?
SOTimeSaved             Think back to the last time you solved a coding problem using Stack Overflow, as well as the las...
SOHowMuchTime                          About how much time did you save? If you're not sure, please use your best estimate.
SOAccount                                                                             Do you have a Stack Overflow account?
SOPartFreq              How frequently would you say you participate in Q&A on Stack Overflow? By participate we mean as...
SOJobs                                                                   Have you ever used or visited Stack Overflow Jobs?
EntTeams                                      Have you ever used Stack Overflow for Enterprise or Stack Overflow for Teams?
SOComm                                                   Do you consider yourself a member of the Stack Overflow community?
WelcomeChange                                             Compared to last year, how welcome do you feel on Stack Overflow?
SONewContent                            Would you like to see any of the following on Stack Overflow? Check all that apply.
Age                            What is your age (in years)? If you prefer not to answer, you may leave this question blank.
Gender                  Which of the following do you currently identify as? Please select all that apply. If you prefer...
Trans                                                                                       Do you identify as transgender?
Sexuality               Which of the following do you currently identify as? Please select all that apply. If you prefer...
Ethnicity               Which of the following do you identify as? Please check all that apply. If you prefer not to ans...
Dependents                                Do you have any dependents (e.g., children, elders, or others) that you care for?
SurveyLength                                                      How do you feel about the length of the survey this year?
SurveyEase                                                               How easy or difficult was this survey to complete?

In [ ]:
schema_df2['QuestionText'] #Will Access the QuestionText column

Column
Respondent                                             Randomized respondent ID number (not in order of survey response time)
MainBranch                Which of the following options best describes you today? Here, by "developer" we mean "someone w...
Hobbyist                                                                                              Do you code as a hobby?
OpenSourcer                                                                       How often do you contribute to open source?
OpenSource                                                   How do you feel about the quality of open source software (OSS)?
Employment                                              Which of the following best describes your current employment status?
Country                                                                             In which country do you currently reside?
Student                                Are you currently enrolled in a formal, degree-granting college or university program?
EdLevel                    Which of the following best describes the highest level of formal education that you’ve completed?
UndergradMajor                                                           What was your main or most important field of study?
EduOther                  Which of the following types of non-degree education have you used or participated in? Please se...
OrgSize                               Approximately how many people are employed by the company or organization you work for?
DevType                                                    Which of the following describe you? Please select all that apply.
YearsCode                                                       Including any education, how many years have you been coding?
Age1stCode                At what age did you write your first line of code or program? (E.g., webpage, Hello World, Scrat...
YearsCodePro                                           How many years have you coded professionally (as a part of your work)?
CareerSat                                                           Overall, how satisfied are you with your career thus far?
JobSat                    How satisfied are you with your current job? (If you work multiple jobs, answer for the one you ...
MgrIdiot                                                    How confident are you that your manager knows what they’re doing?
MgrMoney                                                     Do you believe that you need to be a manager to make more money?
MgrWant                                                               Do you want to become a manager yourself in the future?
JobSeek                                                Which of the following best describes your current job-seeking status?
LastHireDate                                                  When was the last time that you took a job with a new employer?
LastInt                   In your most recent successful job interview (resulting in a job offer), you were asked to... (c...
FizzBuzz                                                          Have you ever been asked to solve FizzBuzz in an interview?
JobFactors                Imagine that you are deciding between two job offers with the same compensation, benefits, and l...
ResumeUpdate              Think back to the last time you updated your resumé, CV, or an online profile on a job site. Wha...
CurrencySymbol            Which currency do you use day-to-day? If your answer is complicated, please pick the one you're ...
CurrencyDesc              Which currency do you use day-to-day? If your answer is complicated, please pick the one you're ...
CompTotal                 What is your current total compensation (salary, bonuses, and perks, before taxes and deductions...
CompFreq                                                                     Is that compensation weekly, monthly, or yearly?
ConvertedComp             Salary converted to annual USD salaries using the exchange rate on 2019-02-01, assuming 12 worki...
WorkWeekHrs                                                                  On average, how many hours per week do you work?
WorkPlan                                                                              How structured or planned is your work?
WorkChallenge             Of these options, what are your greatest challenges to productivity as a developer? Select up to 3:
WorkRemote                                                                                    How often do you work remotely?
WorkLoc                                                                                       Where would you prefer to work?
ImpSyn                    For the specific work you do, and the years of experience you have, how do you rate your own lev...
CodeRev                                                                              Do you review code as part of your work?
CodeRevHrs                                                   On average, how many hours per week do you spend on code review?
UnitTests                                 Does your company regularly employ unit tests in the development of their products?
PurchaseHow                 How does your company make decisions about purchasing new technology (cloud, AI, IoT, databases)?
PurchaseWhat              What level of influence do you, personally, have over new technology purchases at your organizat...
LanguageWorkedWith        Which of the following programming, scripting, and markup languages have you done extensive deve...
LanguageDesireNextYear    Which of the following programming, scripting, and markup languages have you done extensive deve...
DatabaseWorkedWith        Which of the following database environments have you done extensive development work in over th...
DatabaseDesireNextYear    Which of the following database environments have you done extensive development work in over th...
PlatformWorkedWith        Which of the following platforms have you done extensive development work for over the past year...
PlatformDesireNextYear    Which of the following platforms have you done extensive development work for over the past year...
WebFrameWorkedWith        Which of the following web frameworks have you done extensive development work in over the past ...
WebFrameDesireNextYear    Which of the following web frameworks have you done extensive development work in over the past ...
MiscTechWorkedWith        Which of the following other frameworks, libraries, and tools have you done extensive developmen...
MiscTechDesireNextYear    Which of the following other frameworks, libraries, and tools have you done extensive developmen...
DevEnviron                               Which development environment(s) do you use regularly?  Please check all that apply.
OpSys                                                                 What is the primary operating system in which you work?
Containers                                         How do you use containers (Docker, Open Container Initiative (OCI), etc.)?
BlockchainOrg                                  How is your organization thinking about or implementing blockchain technology?
BlockchainIs                                                             Blockchain / cryptocurrency technology is primarily:
BetterLife                                         Do you think people born today will have a better life than their parents?
ITperson                                                                     Are you the "IT support person" for your family?
OffOn                                                                             Have you tried turning it off and on again?
SocialMedia                                                                       What social media site do you use the most?
Extraversion                                                                  Do you prefer online chat or IRL conversations?
ScreenName                                                                                               What do you call it?
SOVisit1st                                               To the best of your memory, when did you first visit Stack Overflow?
SOVisitFreq                                                            How frequently would you say you visit Stack Overflow?
SOVisitTo                                                                 I visit Stack Overflow to... (check all that apply)
SOFindAnswer                             On average, how many times a week do you find (and use) an answer on Stack Overflow?
SOTimeSaved               Think back to the last time you solved a coding problem using Stack Overflow, as well as the las...
SOHowMuchTime                            About how much time did you save? If you're not sure, please use your best estimate.
SOAccount                                                                               Do you have a Stack Overflow account?
SOPartFreq                How frequently would you say you participate in Q&A on Stack Overflow? By participate we mean as...
SOJobs                                                                     Have you ever used or visited Stack Overflow Jobs?
EntTeams                                        Have you ever used Stack Overflow for Enterprise or Stack Overflow for Teams?
SOComm                                                     Do you consider yourself a member of the Stack Overflow community?
WelcomeChange                                               Compared to last year, how welcome do you feel on Stack Overflow?
SONewContent                              Would you like to see any of the following on Stack Overflow? Check all that apply.
Age                              What is your age (in years)? If you prefer not to answer, you may leave this question blank.
Gender                    Which of the following do you currently identify as? Please select all that apply. If you prefer...
Trans                                                                                         Do you identify as transgender?
Sexuality                 Which of the following do you currently identify as? Please select all that apply. If you prefer...
Ethnicity                 Which of the following do you identify as? Please check all that apply. If you prefer not to ans...
Dependents                                  Do you have any dependents (e.g., children, elders, or others) that you care for?
SurveyLength                                                        How do you feel about the length of the survey this year?
SurveyEase                                                                 How easy or difficult was this survey to complete?
Name: QuestionText, dtype: object

In [34]:
#schema_df2['Hobbyist']
#will give error as Hobbyist is not a column

In [35]:
schema_df2.loc['Hobbyist']
#Will give data present at value QuestionText  for Hobbyist key

QuestionText    Do you code as a hobby?
Name: Hobbyist, dtype: object

In [38]:
#schema_df2['MgrIdiot']
#this will give error as MgrIdiot is not a column in the schema dataframe

In [ ]:
schema_df2.loc['MgrIdiot','QuestionText']

'How confident are you that your manager knows what they’re doing?'

In [ ]:
schema_df2.sort_index() 
#will ascending sort the original dataframe based on indexes i.e. rows
# if strings (then alphabetically) if number then increasing value based
# this will update original dataframe 
# if you want to update original dataframe we can use inplace=True

                                                                                                               QuestionText
Column
Age                            What is your age (in years)? If you prefer not to answer, you may leave this question blank.
Age1stCode              At what age did you write your first line of code or program? (E.g., webpage, Hello World, Scrat...
BetterLife                                       Do you think people born today will have a better life than their parents?
BlockchainIs                                                           Blockchain / cryptocurrency technology is primarily:
BlockchainOrg                                How is your organization thinking about or implementing blockchain technology?
CareerSat                                                         Overall, how satisfied are you with your career thus far?
CodeRev                                                                            Do you review code as part of your work?
CodeRevHrs                                                 On average, how many hours per week do you spend on code review?
CompFreq                                                                   Is that compensation weekly, monthly, or yearly?
CompTotal               What is your current total compensation (salary, bonuses, and perks, before taxes and deductions...
Containers                                       How do you use containers (Docker, Open Container Initiative (OCI), etc.)?
ConvertedComp           Salary converted to annual USD salaries using the exchange rate on 2019-02-01, assuming 12 worki...
Country                                                                           In which country do you currently reside?
CurrencyDesc            Which currency do you use day-to-day? If your answer is complicated, please pick the one you're ...
CurrencySymbol          Which currency do you use day-to-day? If your answer is complicated, please pick the one you're ...
DatabaseDesireNextYear  Which of the following database environments have you done extensive development work in over th...
DatabaseWorkedWith      Which of the following database environments have you done extensive development work in over th...
Dependents                                Do you have any dependents (e.g., children, elders, or others) that you care for?
DevEnviron                             Which development environment(s) do you use regularly?  Please check all that apply.
DevType                                                  Which of the following describe you? Please select all that apply.
EdLevel                  Which of the following best describes the highest level of formal education that you’ve completed?
EduOther                Which of the following types of non-degree education have you used or participated in? Please se...
Employment                                            Which of the following best describes your current employment status?
EntTeams                                      Have you ever used Stack Overflow for Enterprise or Stack Overflow for Teams?
Ethnicity               Which of the following do you identify as? Please check all that apply. If you prefer not to ans...
Extraversion                                                                Do you prefer online chat or IRL conversations?
FizzBuzz                                                        Have you ever been asked to solve FizzBuzz in an interview?
Gender                  Which of the following do you currently identify as? Please select all that apply. If you prefer...
Hobbyist                                                                                            Do you code as a hobby?
ITperson                                                                   Are you the "IT support person" for your family?
ImpSyn                  For the specific work you do, and the years of experience you have, how do you rate your own lev...
JobFactors              Imagine that you are deciding between two job offers with the same compensation, benefits, and l...
JobSat                  How satisfied are you with your current job? (If you work multiple jobs, answer for the one you ...
JobSeek                                              Which of the following best describes your current job-seeking status?
LanguageDesireNextYear  Which of the following programming, scripting, and markup languages have you done extensive deve...
LanguageWorkedWith      Which of the following programming, scripting, and markup languages have you done extensive deve...
LastHireDate                                                When was the last time that you took a job with a new employer?
LastInt                 In your most recent successful job interview (resulting in a job offer), you were asked to... (c...
MainBranch              Which of the following options best describes you today? Here, by "developer" we mean "someone w...
MgrIdiot                                                  How confident are you that your manager knows what they’re doing?
MgrMoney                                                   Do you believe that you need to be a manager to make more money?
MgrWant                                                             Do you want to become a manager yourself in the future?
MiscTechDesireNextYear  Which of the following other frameworks, libraries, and tools have you done extensive developmen...
MiscTechWorkedWith      Which of the following other frameworks, libraries, and tools have you done extensive developmen...
OffOn                                                                           Have you tried turning it off and on again?
OpSys                                                               What is the primary operating system in which you work?
OpenSource                                                 How do you feel about the quality of open source software (OSS)?
OpenSourcer                                                                     How often do you contribute to open source?
OrgSize                             Approximately how many people are employed by the company or organization you work for?
PlatformDesireNextYear  Which of the following platforms have you done extensive development work for over the past year...
PlatformWorkedWith      Which of the following platforms have you done extensive development work for over the past year...
PurchaseHow               How does your company make decisions about purchasing new technology (cloud, AI, IoT, databases)?
PurchaseWhat            What level of influence do you, personally, have over new technology purchases at your organizat...
Respondent                                           Randomized respondent ID number (not in order of survey response time)
ResumeUpdate            Think back to the last time you updated your resumé, CV, or an online profile on a job site. Wha...
SOAccount                                                                             Do you have a Stack Overflow account?
SOComm                                                   Do you consider yourself a member of the Stack Overflow community?
SOFindAnswer                           On average, how many times a week do you find (and use) an answer on Stack Overflow?
SOHowMuchTime                          About how much time did you save? If you're not sure, please use your best estimate.
SOJobs                                                                   Have you ever used or visited Stack Overflow Jobs?
SONewContent                            Would you like to see any of the following on Stack Overflow? Check all that apply.
SOPartFreq              How frequently would you say you participate in Q&A on Stack Overflow? By participate we mean as...
SOTimeSaved             Think back to the last time you solved a coding problem using Stack Overflow, as well as the las...
SOVisit1st                                             To the best of your memory, when did you first visit Stack Overflow?
SOVisitFreq                                                          How frequently would you say you visit Stack Overflow?
SOVisitTo                                                               I visit Stack Overflow to... (check all that apply)
ScreenName                                                                                             What do you call it?
Sexuality               Which of the following do you currently identify as? Please select all that apply. If you prefer...
SocialMedia                                                                     What social media site do you use the most?
Student                              Are you currently enrolled in a formal, degree-granting college or university program?
SurveyEase                                                               How easy or difficult was this survey to complete?
SurveyLength                                                      How do you feel about the length of the survey this year?
Trans                                                                                       Do you identify as transgender?
UndergradMajor                                                         What was your main or most important field of study?
UnitTests                               Does your company regularly employ unit tests in the development of their products?
WebFrameDesireNextYear  Which of the following web frameworks have you done extensive development work in over the past ...
WebFrameWorkedWith      Which of the following web frameworks have you done extensive development work in over the past ...
WelcomeChange                                             Compared to last year, how welcome do you feel on Stack Overflow?
WorkChallenge           Of these options, what are your greatest challenges to productivity as a developer? Select up to 3:
WorkLoc                                                                                     Where would you prefer to work?
WorkPlan                                                                            How structured or planned is your work?
WorkRemote                                                                                  How often do you work remotely?
WorkWeekHrs                                                                On average, how many hours per week do you work?
YearsCode                                                     Including any education, how many years have you been coding?
YearsCodePro                                         How many years have you coded professionally (as a part of your work)?

In [41]:
schema_df2.sort_index(ascending=False)

                                                                                                               QuestionText
Column
YearsCodePro                                         How many years have you coded professionally (as a part of your work)?
YearsCode                                                     Including any education, how many years have you been coding?
WorkWeekHrs                                                                On average, how many hours per week do you work?
WorkRemote                                                                                  How often do you work remotely?
WorkPlan                                                                            How structured or planned is your work?
WorkLoc                                                                                     Where would you prefer to work?
WorkChallenge           Of these options, what are your greatest challenges to productivity as a developer? Select up to 3:
WelcomeChange                                             Compared to last year, how welcome do you feel on Stack Overflow?
WebFrameWorkedWith      Which of the following web frameworks have you done extensive development work in over the past ...
WebFrameDesireNextYear  Which of the following web frameworks have you done extensive development work in over the past ...
UnitTests                               Does your company regularly employ unit tests in the development of their products?
UndergradMajor                                                         What was your main or most important field of study?
Trans                                                                                       Do you identify as transgender?
SurveyLength                                                      How do you feel about the length of the survey this year?
SurveyEase                                                               How easy or difficult was this survey to complete?
Student                              Are you currently enrolled in a formal, degree-granting college or university program?
SocialMedia                                                                     What social media site do you use the most?
Sexuality               Which of the following do you currently identify as? Please select all that apply. If you prefer...
ScreenName                                                                                             What do you call it?
SOVisitTo                                                               I visit Stack Overflow to... (check all that apply)
SOVisitFreq                                                          How frequently would you say you visit Stack Overflow?
SOVisit1st                                             To the best of your memory, when did you first visit Stack Overflow?
SOTimeSaved             Think back to the last time you solved a coding problem using Stack Overflow, as well as the las...
SOPartFreq              How frequently would you say you participate in Q&A on Stack Overflow? By participate we mean as...
SONewContent                            Would you like to see any of the following on Stack Overflow? Check all that apply.
SOJobs                                                                   Have you ever used or visited Stack Overflow Jobs?
SOHowMuchTime                          About how much time did you save? If you're not sure, please use your best estimate.
SOFindAnswer                           On average, how many times a week do you find (and use) an answer on Stack Overflow?
SOComm                                                   Do you consider yourself a member of the Stack Overflow community?
SOAccount                                                                             Do you have a Stack Overflow account?
ResumeUpdate            Think back to the last time you updated your resumé, CV, or an online profile on a job site. Wha...
Respondent                                           Randomized respondent ID number (not in order of survey response time)
PurchaseWhat            What level of influence do you, personally, have over new technology purchases at your organizat...
PurchaseHow               How does your company make decisions about purchasing new technology (cloud, AI, IoT, databases)?
PlatformWorkedWith      Which of the following platforms have you done extensive development work for over the past year...
PlatformDesireNextYear  Which of the following platforms have you done extensive development work for over the past year...
OrgSize                             Approximately how many people are employed by the company or organization you work for?
OpenSourcer                                                                     How often do you contribute to open source?
OpenSource                                                 How do you feel about the quality of open source software (OSS)?
OpSys                                                               What is the primary operating system in which you work?
OffOn                                                                           Have you tried turning it off and on again?
MiscTechWorkedWith      Which of the following other frameworks, libraries, and tools have you done extensive developmen...
MiscTechDesireNextYear  Which of the following other frameworks, libraries, and tools have you done extensive developmen...
MgrWant                                                             Do you want to become a manager yourself in the future?
MgrMoney                                                   Do you believe that you need to be a manager to make more money?
MgrIdiot                                                  How confident are you that your manager knows what they’re doing?
MainBranch              Which of the following options best describes you today? Here, by "developer" we mean "someone w...
LastInt                 In your most recent successful job interview (resulting in a job offer), you were asked to... (c...
LastHireDate                                                When was the last time that you took a job with a new employer?
LanguageWorkedWith      Which of the following programming, scripting, and markup languages have you done extensive deve...
LanguageDesireNextYear  Which of the following programming, scripting, and markup languages have you done extensive deve...
JobSeek                                              Which of the following best describes your current job-seeking status?
JobSat                  How satisfied are you with your current job? (If you work multiple jobs, answer for the one you ...
JobFactors              Imagine that you are deciding between two job offers with the same compensation, benefits, and l...
ImpSyn                  For the specific work you do, and the years of experience you have, how do you rate your own lev...
ITperson                                                                   Are you the "IT support person" for your family?
Hobbyist                                                                                            Do you code as a hobby?
Gender                  Which of the following do you currently identify as? Please select all that apply. If you prefer...
FizzBuzz                                                        Have you ever been asked to solve FizzBuzz in an interview?
Extraversion                                                                Do you prefer online chat or IRL conversations?
Ethnicity               Which of the following do you identify as? Please check all that apply. If you prefer not to ans...
EntTeams                                      Have you ever used Stack Overflow for Enterprise or Stack Overflow for Teams?
Employment                                            Which of the following best describes your current employment status?
EduOther                Which of the following types of non-degree education have you used or participated in? Please se...
EdLevel                  Which of the following best describes the highest level of formal education that you’ve completed?
DevType                                                  Which of the following describe you? Please select all that apply.
DevEnviron                             Which development environment(s) do you use regularly?  Please check all that apply.
Dependents                                Do you have any dependents (e.g., children, elders, or others) that you care for?
DatabaseWorkedWith      Which of the following database environments have you done extensive development work in over th...
DatabaseDesireNextYear  Which of the following database environments have you done extensive development work in over th...
CurrencySymbol          Which currency do you use day-to-day? If your answer is complicated, please pick the one you're ...
CurrencyDesc            Which currency do you use day-to-day? If your answer is complicated, please pick the one you're ...
Country                                                                           In which country do you currently reside?
ConvertedComp           Salary converted to annual USD salaries using the exchange rate on 2019-02-01, assuming 12 worki...
Containers                                       How do you use containers (Docker, Open Container Initiative (OCI), etc.)?
CompTotal               What is your current total compensation (salary, bonuses, and perks, before taxes and deductions...
CompFreq                                                                   Is that compensation weekly, monthly, or yearly?
CodeRevHrs                                                 On average, how many hours per week do you spend on code review?
CodeRev                                                                            Do you review code as part of your work?
CareerSat                                                         Overall, how satisfied are you with your career thus far?
BlockchainOrg                                How is your organization thinking about or implementing blockchain technology?
BlockchainIs                                                           Blockchain / cryptocurrency technology is primarily:
BetterLife                                       Do you think people born today will have a better life than their parents?
Age1stCode              At what age did you write your first line of code or program? (E.g., webpage, Hello World, Scrat...
Age                            What is your age (in years)? If you prefer not to answer, you may leave this question blank.