In [1]:
import pandas as pd
df = pd.read_csv('./Data_2019/survey_results_public.csv')
schema_df = pd.read_csv('./Data_2019/survey_results_schema.csv')
pd.set_option('display.max_columns', 85) #to display all columns in the dataframe
pd.set_option('display.max_rows', 85)   #to see all rows in the dataframe of schema

In [2]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [3]:
df['SocialMedia'] == 'Twitter'

0         True
1        False
2        False
3        False
4        False
         ...
88878    False
88879    False
88880    False
88881    False
88882    False
Name: SocialMedia, Length: 88883, dtype: bool

In [5]:
filt1 = (df['SocialMedia'] == 'Twitter')

In [6]:
df[filt1]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
8,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,"Database administrator;Developer, back-end;Dev...",12,11,4,Slightly satisfied,Slightly satisfied,Somewhat confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Interview with people in peer r...,Yes,Financial performance or funding status of the...,I was preparing for a job search,NZD,New Zealand dollar,138000.0,Yearly,95179.0,32.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",12.0,"Yes, it's not part of our process but the deve...",Not sure,I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,Bash/Shell/PowerShell;C;HTML/CSS;JavaScript;Ru...,DynamoDB;PostgreSQL;SQLite,PostgreSQL;Redis;SQLite,AWS;Docker;Heroku;Linux;MacOS;Slack,AWS;Docker;Heroku;Linux;MacOS;Slack;Other(s):,Express;Ruby on Rails;Other(s):,Express;Ruby on Rails;Other(s):,Node.js;Unity 3D,Node.js,Vim,MacOS,Development;Testing;Production,Not at all,An irresponsible use of resources,No,SIGH,Yes,Twitter,In real life (in person),Username,2013,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
12,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,Data or business analyst;Database administrato...,17,11,8,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Complete a take-home project;Interview with pe...,Yes,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,90000.0,Yearly,90000.0,40.0,There is a schedule and/or spec (made by me or...,"Meetings;Non-work commitments (parenting, scho...",All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Rust...,Couchbase;DynamoDB;Firebase;MySQL,Firebase;MySQL;Redis,Android;AWS;Docker;IBM Cloud or Watson;iOS;Lin...,Android;AWS;Docker;IBM Cloud or Watson;Linux;S...,Angular/Angular.js;ASP.NET;Express;jQuery;Vue.js,Express;Vue.js,Node.js;Xamarin,Node.js;TensorFlow,Vim;Visual Studio;Visual Studio Code;Xcode,Windows,Development;Testing;Production,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,Twitter,In real life (in person),Username,2011,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
43,44,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, back-end;Developer, desktop or ente...",26,12,19,Slightly satisfied,Neither satisfied nor dissatisfied,Not at all confident,No,Not sure,"I’m not actively looking, but I am open to new...",More than 4 years ago,Interview with people in peer roles;Interview ...,No,Specific department or team I'd be working on;...,"My job status changed (promotion, new job, etc.)",EUR,European Euro,6400.0,Monthly,87996.0,39.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Far above average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...,C#,Oracle;Other(s):,Other(s):,Linux;Windows,Docker;Linux;Microsoft Azure;Windows,Spring;Vue.js,Spring;Vue.js;Other(s):,.NET;.NET Core,.NET;.NET Core,IntelliJ;Visual Studio;Visual Studio Code,Windows,"Outside of work, for personal projects",Non-currency applications of blockchain,Useful for immutable record keeping outside of...,Yes,Also Yes,Yes,Twitter,In real life (in person),Login,2010,A few times per week,Find answers to specific questions;Contribute ...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,43.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
59,60,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Secondary school (e.g. American high school, G...",NaN,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Developer, back-end;DevOps specialist",10,13,9,Slightly satisfied,Neither satisfied nor dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,1-2 years ago,Complete a take-home project;Interview with pe...,Yes,"Industry that I'd be working in;Languages, fra...","My job status changed (promotion, new job, etc.)",USD,United States dollar,107000.0,Yearly,107000.0,46.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,A few days each month,Office,Average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have some influence,Bash/Shell/PowerShell;Go;JavaScript;PHP;Python...,Bash/Shell/PowerShell;C++;Go;Kotlin;Python;Typ...,DynamoDB;Elasticsearch;MariaDB;MySQL;Redis;Oth...,Elasticsearch;MySQL;PostgreSQL;Redis,AWS;Docker;Kubernetes,AWS;Docker;Google Cloud Platform;Kubernetes;Ra...,Flask;Laravel;React.js;Vue.js;Other(s):,Laravel;Vue.js;Other(s):,Ansible;Chef;Node.js;Puppet,Ansible;Node.js;React Native;TensorFlow,PHPStorm;Vim;Visual Studio Code,MacOS,"Development;Testing;Outside of work, for perso...",Non-currency applications of blockchain,An irresponsible use of resources,No,"Fortunately, someone else has that title",Yes,Twitter,Neither,Username,2010,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",NaN,Industry news about technologies you're intere...,27.0,Man,No,Bisexual,White or of European descent,No,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88836,81934,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Oman,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,20,19,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C#;Python;R;SQL,C#;Python,Microsoft SQL Server;PostgreSQL,PostgreSQL,Android;Windows,Android;Arduino;Windows,NaN,ASP.NET,Xamarin,Xamarin,Visual Studio,Windows,I do not use containers,NaN,A passing fad,No,SIGH,Yes,Twitter,In real life (in person),Username,NaN,A few times per month or weekly,Find answers to specific questions;Pass the ti...,Less than once per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Tech...,NaN,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
88850,83786,NaN,No,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",500 to 999 employees,Academic researcher,36,21,29,NaN,NaN,Not at all confident,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Kotlin;TypeScript,HTML/CSS;JavaScript;Kotlin;TypeScript,MongoDB,MongoDB,Android;Windows,Android;Docker;Heroku;Kubernetes;Windows,Angular/Angular.js;Express;React.js;Spring,Angular/Angular.js;React.js;Spring,Node.js,Node.js;React Native,Android Studio;IntelliJ;Notepad++;Visual Studi...,Windows,I do not use containers,NaN,NaN,No,Yes,No,Twitter,Neither,NaN,2008,Daily or almost daily,Find answers to specific questions;Contribute ...,Less than once per week,They were about the same,NaN,Yes,A few times per month or weekly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,57.0,Man,No,NaN,White or of European descent,Yes,Too long,Neither easy nor difficult
88852,83862,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,Participated in a hackathon,NaN,Data or business analyst;Student,1,18,Less than 1 year,NaN,NaN,Very confident,Not sure,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;C++;HTML/CSS;Java;JavaScript;Object...,NaN,MySQL,DynamoDB;Elasticsearch;MongoDB,Android;AWS;Google Cloud Platform;WordPress,IBM Cloud or Watson,Laravel,Angular/Angular.js;Laravel;Vue.js,NaN,Node.js,Android Studio;Atom;IntelliJ;Komodo;NetBeans;N...,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,No,Yes,What?,Twitter,Online,UserID,2012,A few times per month or weekly,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was much faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
88857,85396,NaN,No,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Sweden,No,"Professional degree (JD, MD, etc.)",NaN,Taken an online course in programming or softw...,100 to 499 employees,Senior executive/VP,4,30,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;PHP;R;SQL,Java;Scala,MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Firebase,Android;Docker;Linux;MacOS,Android;Docker;Linux;MacOS;Raspberry Pi,NaN,Django;jQuery,Hadoop;Pandas;Torch/PyTorch,Hadoop;TensorFlow,Android Studio;Atom;IntelliJ;IPython / Jupyter...,Linux-based,"Outside of work, for personal projects",NaN,Useful across many domains and could change ma...,Yes,Yes,What?,Twitter,In real life (in person),NaN,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",A lot less welcome now than last year,Tech meetups or events in your area,NaN,Man,No,Straight / Heterosexual,Black or of African descent,NaN,Too long,Neither easy nor difficult
88875,88182,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Pakistan,NaN,"Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,10 to 19 employees,Academic researcher,1,Younger than 5 years,Less than 1 year,NaN,NaN,Very confident,Not sure,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,NaN,NaN,NaN,Google Cloud Platform,NaN,Other(s):,NaN,Other(s):,NaN,Android Studio,Windows,Development,NaN,Useful across many domains and could change ma...,Yes,Also Yes,What?,Twitter,Neither,Username,NaN,I have never visited Stack Overflow (before to...,Get a sense of belonging to the developer comm...,Less than once per week,The other resource was slightly faster,60+ minutes,NaN,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Not applicable - I did not use Stack Overflow ...,Courses on technologies you're interested in,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too short,Neither easy nor difficult

In [7]:
df[df['SocialMedia'] == 'Twitter']

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
8,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,"Database administrator;Developer, back-end;Dev...",12,11,4,Slightly satisfied,Slightly satisfied,Somewhat confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Interview with people in peer r...,Yes,Financial performance or funding status of the...,I was preparing for a job search,NZD,New Zealand dollar,138000.0,Yearly,95179.0,32.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",12.0,"Yes, it's not part of our process but the deve...",Not sure,I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,Bash/Shell/PowerShell;C;HTML/CSS;JavaScript;Ru...,DynamoDB;PostgreSQL;SQLite,PostgreSQL;Redis;SQLite,AWS;Docker;Heroku;Linux;MacOS;Slack,AWS;Docker;Heroku;Linux;MacOS;Slack;Other(s):,Express;Ruby on Rails;Other(s):,Express;Ruby on Rails;Other(s):,Node.js;Unity 3D,Node.js,Vim,MacOS,Development;Testing;Production,Not at all,An irresponsible use of resources,No,SIGH,Yes,Twitter,In real life (in person),Username,2013,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
12,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,Data or business analyst;Database administrato...,17,11,8,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Complete a take-home project;Interview with pe...,Yes,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,90000.0,Yearly,90000.0,40.0,There is a schedule and/or spec (made by me or...,"Meetings;Non-work commitments (parenting, scho...",All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Rust...,Couchbase;DynamoDB;Firebase;MySQL,Firebase;MySQL;Redis,Android;AWS;Docker;IBM Cloud or Watson;iOS;Lin...,Android;AWS;Docker;IBM Cloud or Watson;Linux;S...,Angular/Angular.js;ASP.NET;Express;jQuery;Vue.js,Express;Vue.js,Node.js;Xamarin,Node.js;TensorFlow,Vim;Visual Studio;Visual Studio Code;Xcode,Windows,Development;Testing;Production,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,Twitter,In real life (in person),Username,2011,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
43,44,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, back-end;Developer, desktop or ente...",26,12,19,Slightly satisfied,Neither satisfied nor dissatisfied,Not at all confident,No,Not sure,"I’m not actively looking, but I am open to new...",More than 4 years ago,Interview with people in peer roles;Interview ...,No,Specific department or team I'd be working on;...,"My job status changed (promotion, new job, etc.)",EUR,European Euro,6400.0,Monthly,87996.0,39.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Far above average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...,C#,Oracle;Other(s):,Other(s):,Linux;Windows,Docker;Linux;Microsoft Azure;Windows,Spring;Vue.js,Spring;Vue.js;Other(s):,.NET;.NET Core,.NET;.NET Core,IntelliJ;Visual Studio;Visual Studio Code,Windows,"Outside of work, for personal projects",Non-currency applications of blockchain,Useful for immutable record keeping outside of...,Yes,Also Yes,Yes,Twitter,In real life (in person),Login,2010,A few times per week,Find answers to specific questions;Contribute ...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,43.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
59,60,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Secondary school (e.g. American high school, G...",NaN,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Developer, back-end;DevOps specialist",10,13,9,Slightly satisfied,Neither satisfied nor dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,1-2 years ago,Complete a take-home project;Interview with pe...,Yes,"Industry that I'd be working in;Languages, fra...","My job status changed (promotion, new job, etc.)",USD,United States dollar,107000.0,Yearly,107000.0,46.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,A few days each month,Office,Average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have some influence,Bash/Shell/PowerShell;Go;JavaScript;PHP;Python...,Bash/Shell/PowerShell;C++;Go;Kotlin;Python;Typ...,DynamoDB;Elasticsearch;MariaDB;MySQL;Redis;Oth...,Elasticsearch;MySQL;PostgreSQL;Redis,AWS;Docker;Kubernetes,AWS;Docker;Google Cloud Platform;Kubernetes;Ra...,Flask;Laravel;React.js;Vue.js;Other(s):,Laravel;Vue.js;Other(s):,Ansible;Chef;Node.js;Puppet,Ansible;Node.js;React Native;TensorFlow,PHPStorm;Vim;Visual Studio Code,MacOS,"Development;Testing;Outside of work, for perso...",Non-currency applications of blockchain,An irresponsible use of resources,No,"Fortunately, someone else has that title",Yes,Twitter,Neither,Username,2010,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",NaN,Industry news about technologies you're intere...,27.0,Man,No,Bisexual,White or of European descent,No,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88836,81934,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Oman,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,20,19,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C#;Python;R;SQL,C#;Python,Microsoft SQL Server;PostgreSQL,PostgreSQL,Android;Windows,Android;Arduino;Windows,NaN,ASP.NET,Xamarin,Xamarin,Visual Studio,Windows,I do not use containers,NaN,A passing fad,No,SIGH,Yes,Twitter,In real life (in person),Username,NaN,A few times per month or weekly,Find answers to specific questions;Pass the ti...,Less than once per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Tech...,NaN,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
88850,83786,NaN,No,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",500 to 999 employees,Academic researcher,36,21,29,NaN,NaN,Not at all confident,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Kotlin;TypeScript,HTML/CSS;JavaScript;Kotlin;TypeScript,MongoDB,MongoDB,Android;Windows,Android;Docker;Heroku;Kubernetes;Windows,Angular/Angular.js;Express;React.js;Spring,Angular/Angular.js;React.js;Spring,Node.js,Node.js;React Native,Android Studio;IntelliJ;Notepad++;Visual Studi...,Windows,I do not use containers,NaN,NaN,No,Yes,No,Twitter,Neither,NaN,2008,Daily or almost daily,Find answers to specific questions;Contribute ...,Less than once per week,They were about the same,NaN,Yes,A few times per month or weekly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,57.0,Man,No,NaN,White or of European descent,Yes,Too long,Neither easy nor difficult
88852,83862,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,Participated in a hackathon,NaN,Data or business analyst;Student,1,18,Less than 1 year,NaN,NaN,Very confident,Not sure,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;C++;HTML/CSS;Java;JavaScript;Object...,NaN,MySQL,DynamoDB;Elasticsearch;MongoDB,Android;AWS;Google Cloud Platform;WordPress,IBM Cloud or Watson,Laravel,Angular/Angular.js;Laravel;Vue.js,NaN,Node.js,Android Studio;Atom;IntelliJ;Komodo;NetBeans;N...,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,No,Yes,What?,Twitter,Online,UserID,2012,A few times per month or weekly,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was much faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
88857,85396,NaN,No,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Sweden,No,"Professional degree (JD, MD, etc.)",NaN,Taken an online course in programming or softw...,100 to 499 employees,Senior executive/VP,4,30,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;PHP;R;SQL,Java;Scala,MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Firebase,Android;Docker;Linux;MacOS,Android;Docker;Linux;MacOS;Raspberry Pi,NaN,Django;jQuery,Hadoop;Pandas;Torch/PyTorch,Hadoop;TensorFlow,Android Studio;Atom;IntelliJ;IPython / Jupyter...,Linux-based,"Outside of work, for personal projects",NaN,Useful across many domains and could change ma...,Yes,Yes,What?,Twitter,In real life (in person),NaN,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",A lot less welcome now than last year,Tech meetups or events in your area,NaN,Man,No,Straight / Heterosexual,Black or of African descent,NaN,Too long,Neither easy nor difficult
88875,88182,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Pakistan,NaN,"Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,10 to 19 employees,Academic researcher,1,Younger than 5 years,Less than 1 year,NaN,NaN,Very confident,Not sure,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,NaN,NaN,NaN,Google Cloud Platform,NaN,Other(s):,NaN,Other(s):,NaN,Android Studio,Windows,Development,NaN,Useful across many domains and could change ma...,Yes,Also Yes,What?,Twitter,Neither,Username,NaN,I have never visited Stack Overflow (before to...,Get a sense of belonging to the developer comm...,Less than once per week,The other resource was slightly faster,60+ minutes,NaN,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Not applicable - I did not use Stack Overflow ...,Courses on technologies you're interested in,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too short,Neither easy nor difficult

In [9]:
df[filt1].iloc[1]

Respondent                                                                9
MainBranch                                   I am a developer by profession
Hobbyist                                                                Yes
OpenSourcer                                      Once a month or more often
OpenSource                The quality of OSS and closed source software ...
Employment                                               Employed full-time
Country                                                         New Zealand
Student                                                                  No
EdLevel                   Some college/university study without earning ...
UndergradMajor            Computer science, computer engineering, or sof...
EduOther                  Taken an online course in programming or softw...
OrgSize                                                  10 to 19 employees
DevType                   Database administrator;Developer, back-end;Dev...
YearsCode                                                                12
Age1stCode                                                               11
YearsCodePro                                                              4
CareerSat                                                Slightly satisfied
JobSat                                                   Slightly satisfied
MgrIdiot                                                 Somewhat confident
MgrMoney                                                                 No
MgrWant                                                            Not sure
JobSeek                   I’m not actively looking, but I am open to new...
LastHireDate                                           Less than a year ago
LastInt                   Write any code;Interview with people in peer r...
FizzBuzz                                                                Yes
JobFactors                Financial performance or funding status of the...
ResumeUpdate                               I was preparing for a job search
CurrencySymbol                                                          NZD
CurrencyDesc                                             New Zealand dollar
CompTotal                                                            138000
CompFreq                                                             Yearly
ConvertedComp                                                         95179
WorkWeekHrs                                                              32
WorkPlan                  There is a schedule and/or spec (made by me or...
WorkChallenge             Being tasked with non-development work;Inadequ...
WorkRemote                                 Less than once per month / Never
WorkLoc                                                              Office
ImpSyn                                               A little above average
CodeRev                             Yes, because I see value in code review
CodeRevHrs                                                               12
UnitTests                 Yes, it's not part of our process but the deve...
PurchaseHow                                                        Not sure
PurchaseWhat                                          I have some influence
LanguageWorkedWith        Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...
LanguageDesireNextYear    Bash/Shell/PowerShell;C;HTML/CSS;JavaScript;Ru...
DatabaseWorkedWith                               DynamoDB;PostgreSQL;SQLite
DatabaseDesireNextYear                              PostgreSQL;Redis;SQLite
PlatformWorkedWith                      AWS;Docker;Heroku;Linux;MacOS;Slack
PlatformDesireNextYear        AWS;Docker;Heroku;Linux;MacOS;Slack;Other(s):
WebFrameWorkedWith                          Express;Ruby on Rails;Other(s):
WebFrameDesireNextYear                      Express;Ruby on Rails;Other(s):
MiscTechWorkedWith                                         Node.js;Unity 3D
MiscTechDesireNextYear                                              Node.js
DevEnviron                                                              Vim
OpSys                                                                 MacOS
Containers                                   Development;Testing;Production
BlockchainOrg                                                    Not at all
BlockchainIs                              An irresponsible use of resources
BetterLife                                                               No
ITperson                                                               SIGH
OffOn                                                                   Yes
SocialMedia                                                         Twitter
Extraversion                                       In real life (in person)
ScreenName                                                         Username
SOVisit1st                                                             2013
SOVisitFreq                                           Daily or almost daily
SOVisitTo                 Find answers to specific questions;Contribute ...
SOFindAnswer                                             3-5 times per week
SOTimeSaved                                        They were about the same
SOHowMuchTime                                                           NaN
SOAccount                                                               Yes
SOPartFreq                              Less than once per month or monthly
SOJobs                    No, I knew that Stack Overflow had a job board...
EntTeams                                No, and I don't know what those are
SOComm                                                        Yes, somewhat
WelcomeChange                       Just as welcome now as I felt last year
SONewContent                                                            NaN
Age                                                                      23
Gender                                                                  Man
Trans                                                                    No
Sexuality                                                          Bisexual
Ethnicity                                      White or of European descent
Dependents                                                               No
SurveyLength                                          Appropriate in length
SurveyEase                                       Neither easy nor difficult
Name: 8, dtype: object

In [ ]:
df.loc[filt1] # this is same as df[filt1]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
8,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,"Database administrator;Developer, back-end;Dev...",12,11,4,Slightly satisfied,Slightly satisfied,Somewhat confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Interview with people in peer r...,Yes,Financial performance or funding status of the...,I was preparing for a job search,NZD,New Zealand dollar,138000.0,Yearly,95179.0,32.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",12.0,"Yes, it's not part of our process but the deve...",Not sure,I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,Bash/Shell/PowerShell;C;HTML/CSS;JavaScript;Ru...,DynamoDB;PostgreSQL;SQLite,PostgreSQL;Redis;SQLite,AWS;Docker;Heroku;Linux;MacOS;Slack,AWS;Docker;Heroku;Linux;MacOS;Slack;Other(s):,Express;Ruby on Rails;Other(s):,Express;Ruby on Rails;Other(s):,Node.js;Unity 3D,Node.js,Vim,MacOS,Development;Testing;Production,Not at all,An irresponsible use of resources,No,SIGH,Yes,Twitter,In real life (in person),Username,2013,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
12,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,Data or business analyst;Database administrato...,17,11,8,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Complete a take-home project;Interview with pe...,Yes,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,90000.0,Yearly,90000.0,40.0,There is a schedule and/or spec (made by me or...,"Meetings;Non-work commitments (parenting, scho...",All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Rust...,Couchbase;DynamoDB;Firebase;MySQL,Firebase;MySQL;Redis,Android;AWS;Docker;IBM Cloud or Watson;iOS;Lin...,Android;AWS;Docker;IBM Cloud or Watson;Linux;S...,Angular/Angular.js;ASP.NET;Express;jQuery;Vue.js,Express;Vue.js,Node.js;Xamarin,Node.js;TensorFlow,Vim;Visual Studio;Visual Studio Code;Xcode,Windows,Development;Testing;Production,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,Twitter,In real life (in person),Username,2011,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
43,44,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, back-end;Developer, desktop or ente...",26,12,19,Slightly satisfied,Neither satisfied nor dissatisfied,Not at all confident,No,Not sure,"I’m not actively looking, but I am open to new...",More than 4 years ago,Interview with people in peer roles;Interview ...,No,Specific department or team I'd be working on;...,"My job status changed (promotion, new job, etc.)",EUR,European Euro,6400.0,Monthly,87996.0,39.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Far above average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...,C#,Oracle;Other(s):,Other(s):,Linux;Windows,Docker;Linux;Microsoft Azure;Windows,Spring;Vue.js,Spring;Vue.js;Other(s):,.NET;.NET Core,.NET;.NET Core,IntelliJ;Visual Studio;Visual Studio Code,Windows,"Outside of work, for personal projects",Non-currency applications of blockchain,Useful for immutable record keeping outside of...,Yes,Also Yes,Yes,Twitter,In real life (in person),Login,2010,A few times per week,Find answers to specific questions;Contribute ...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,43.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
59,60,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Secondary school (e.g. American high school, G...",NaN,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Developer, back-end;DevOps specialist",10,13,9,Slightly satisfied,Neither satisfied nor dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,1-2 years ago,Complete a take-home project;Interview with pe...,Yes,"Industry that I'd be working in;Languages, fra...","My job status changed (promotion, new job, etc.)",USD,United States dollar,107000.0,Yearly,107000.0,46.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,A few days each month,Office,Average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have some influence,Bash/Shell/PowerShell;Go;JavaScript;PHP;Python...,Bash/Shell/PowerShell;C++;Go;Kotlin;Python;Typ...,DynamoDB;Elasticsearch;MariaDB;MySQL;Redis;Oth...,Elasticsearch;MySQL;PostgreSQL;Redis,AWS;Docker;Kubernetes,AWS;Docker;Google Cloud Platform;Kubernetes;Ra...,Flask;Laravel;React.js;Vue.js;Other(s):,Laravel;Vue.js;Other(s):,Ansible;Chef;Node.js;Puppet,Ansible;Node.js;React Native;TensorFlow,PHPStorm;Vim;Visual Studio Code,MacOS,"Development;Testing;Outside of work, for perso...",Non-currency applications of blockchain,An irresponsible use of resources,No,"Fortunately, someone else has that title",Yes,Twitter,Neither,Username,2010,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",NaN,Industry news about technologies you're intere...,27.0,Man,No,Bisexual,White or of European descent,No,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88836,81934,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Oman,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,20,19,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C#;Python;R;SQL,C#;Python,Microsoft SQL Server;PostgreSQL,PostgreSQL,Android;Windows,Android;Arduino;Windows,NaN,ASP.NET,Xamarin,Xamarin,Visual Studio,Windows,I do not use containers,NaN,A passing fad,No,SIGH,Yes,Twitter,In real life (in person),Username,NaN,A few times per month or weekly,Find answers to specific questions;Pass the ti...,Less than once per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Tech...,NaN,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
88850,83786,NaN,No,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",500 to 999 employees,Academic researcher,36,21,29,NaN,NaN,Not at all confident,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Kotlin;TypeScript,HTML/CSS;JavaScript;Kotlin;TypeScript,MongoDB,MongoDB,Android;Windows,Android;Docker;Heroku;Kubernetes;Windows,Angular/Angular.js;Express;React.js;Spring,Angular/Angular.js;React.js;Spring,Node.js,Node.js;React Native,Android Studio;IntelliJ;Notepad++;Visual Studi...,Windows,I do not use containers,NaN,NaN,No,Yes,No,Twitter,Neither,NaN,2008,Daily or almost daily,Find answers to specific questions;Contribute ...,Less than once per week,They were about the same,NaN,Yes,A few times per month or weekly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,57.0,Man,No,NaN,White or of European descent,Yes,Too long,Neither easy nor difficult
88852,83862,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,Participated in a hackathon,NaN,Data or business analyst;Student,1,18,Less than 1 year,NaN,NaN,Very confident,Not sure,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;C++;HTML/CSS;Java;JavaScript;Object...,NaN,MySQL,DynamoDB;Elasticsearch;MongoDB,Android;AWS;Google Cloud Platform;WordPress,IBM Cloud or Watson,Laravel,Angular/Angular.js;Laravel;Vue.js,NaN,Node.js,Android Studio;Atom;IntelliJ;Komodo;NetBeans;N...,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,No,Yes,What?,Twitter,Online,UserID,2012,A few times per month or weekly,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was much faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
88857,85396,NaN,No,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Sweden,No,"Professional degree (JD, MD, etc.)",NaN,Taken an online course in programming or softw...,100 to 499 employees,Senior executive/VP,4,30,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;PHP;R;SQL,Java;Scala,MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Firebase,Android;Docker;Linux;MacOS,Android;Docker;Linux;MacOS;Raspberry Pi,NaN,Django;jQuery,Hadoop;Pandas;Torch/PyTorch,Hadoop;TensorFlow,Android Studio;Atom;IntelliJ;IPython / Jupyter...,Linux-based,"Outside of work, for personal projects",NaN,Useful across many domains and could change ma...,Yes,Yes,What?,Twitter,In real life (in person),NaN,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",A lot less welcome now than last year,Tech meetups or events in your area,NaN,Man,No,Straight / Heterosexual,Black or of African descent,NaN,Too long,Neither easy nor difficult
88875,88182,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Pakistan,NaN,"Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,10 to 19 employees,Academic researcher,1,Younger than 5 years,Less than 1 year,NaN,NaN,Very confident,Not sure,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,NaN,NaN,NaN,Google Cloud Platform,NaN,Other(s):,NaN,Other(s):,NaN,Android Studio,Windows,Development,NaN,Useful across many domains and could change ma...,Yes,Also Yes,What?,Twitter,Neither,Username,NaN,I have never visited Stack Overflow (before to...,Get a sense of belonging to the developer comm...,Less than once per week,The other resource was slightly faster,60+ minutes,NaN,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Not applicable - I did not use Stack Overflow ...,Courses on technologies you're interested in,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too short,Neither easy nor difficult

In [12]:
df.loc[filt1,'Employment'] #to get the employment column for those who use twitter

0                   Not employed, and not looking for work
8                                       Employed full-time
12                                      Employed full-time
43                                      Employed full-time
59                                      Employed full-time
                               ...
88836               Not employed, and not looking for work
88850                                   Employed full-time
88852                                   Employed full-time
88857    Independent contractor, freelancer, or self-em...
88875                                   Employed part-time
Name: Employment, Length: 11398, dtype: object

In [14]:
filt2 =(df['SocialMedia'] == 'Twitter') & (df['Employment'] == 'Not employed, but looking for work')

In [15]:
df.loc[filt2]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
226,228,"I am not primarily a developer, but I write co...",No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",France,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,Data or business analyst;Data scientist or mac...,7,16,3,Neither satisfied nor dissatisfied,NaN,NaN,NaN,NaN,I am actively looking for a job,Less than a year ago,NaN,NaN,"Languages, frameworks, and other technologies ...",I was preparing for a job search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python;Scala;SQL,HTML/CSS;JavaScript;Python;Scala;SQL,MySQL;PostgreSQL,Elasticsearch;MariaDB;MongoDB,Windows,NaN,jQuery;Laravel;Spring,NaN,Pandas,Apache Spark;Hadoop;Pandas;TensorFlow,Atom;Eclipse;IPython / Jupyter;Sublime Text,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,No,Yes,What?,Twitter,In real life (in person),NaN,2013,A few times per month or weekly,Find answers to specific questions;Contribute ...,1-2 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,NaN,25.0,Man,No,Straight / Heterosexual,Black or of African descent,No,Appropriate in length,Neither easy nor difficult
270,272,I am a student who is learning to code,Yes,Once a month or more often,The quality of OSS and closed source software ...,"Not employed, but looking for work",Serbia,No,"Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, full-stack",1,39,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,More than 4 years ago,NaN,NaN,Remote work options;Opportunities for professi...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;PHP,Java;JavaScript;Objective-C,MariaDB;MySQL,MariaDB;MySQL;Oracle,Android;Windows,Android;MacOS;Windows,ASP.NET,NaN,NaN,NaN,Notepad++;Visual Studio,Windows,Development,NaN,NaN,No,"Fortunately, someone else has that title",Yes,Twitter,Online,UserID,2019,I have never visited Stack Overflow (before to...,Get a sense of belonging to the developer comm...,Less than once per week,Stack Overflow was much faster,11-30 minutes,NaN,NaN,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Not sure,Just as welcome now as I felt last year,Tech articles written by other developers,39.0,Woman,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
282,284,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",Canada,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,Student,3,12,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Industry that I'd be working in;Specific depar...,I was preparing for a job search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C++;C#;Java,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...,NaN,MySQL,NaN,Android;iOS;Raspberry Pi,NaN,NaN,Unity 3D,Unity 3D,IntelliJ;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,A passing fad,Yes,SIGH,What?,Twitter,Neither,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Not applicable - I did not use Stack Overflow ...,Courses on technologies you're interested in,19.0,Man,No,Straight / Heterosexual,East Asian,No,Appropriate in length,Easy
515,517,"I am not primarily a developer, but I write co...",No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,"Yes, part-time",Associate degree,"Another engineering discipline (ex. civil, ele...",Participated in a full-time developer training...,NaN,Data or business analyst;Data scientist or mac...,7,Younger than 5 years,Less than 1 year,Very dissatisfied,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Languages, frameworks, and other technologies ...","Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A little above average,NaN,NaN,NaN,NaN,NaN,Assembly;C++;F#;HTML/CSS;PHP;Python;R;Rust;Typ...,Bash/Shell/PowerShell;C;C#;Java;Ruby;Scala;SQL...,Cassandra;DynamoDB;Firebase;MongoDB;Microsoft ...,Couchbase;Elasticsearch;MariaDB;MySQL;Other(s):,AWS;Docker;Heroku;IBM Cloud or Watson;iOS;MacO...,Android;Arduino;Google Cloud Platform;Kubernet...,ASP.NET;Django;Express;Flask;Laravel;Spring,Angular/Angular.js;Drupal;jQuery;React.js;Ruby...,NaN,Other(s):,Android Studio;Atom;Emacs;IntelliJ;IPython / J...,NaN,"Development;Testing;Outside of work, for perso...",NaN,"Useful for decentralized currency (i.e., Bitcoin)",No,SIGH,Yes,Twitter,In real life (in person),NaN,NaN,Daily or almost daily,Contribute to a library of information;Get a s...,Less than once per week,Stack Overflow was slightly faster,0-10 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, I've heard of them, but I am not part of a...",Neutral,Somewhat less welcome now than last year,Tech articles written by other developers,25.0,"Non-binary, genderqueer, or gender non-conforming",Yes,NaN,NaN,Yes,Too short,Difficult
779,782,I am a student who is learning to code,Yes,Once a month or more often,The quality of OSS and closed source software ...,"Not employed, but looking for work",Kenya,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Designer;Developer, front-end;Developer, full-...",2,18,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",I've never had a job,NaN,NaN,"Languages, frameworks, and other technologies ...",I heard about a job opportunity (from a recrui...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;SQL;VBA,Java;Python;R,MySQL,Oracle;SQLite,Windows,Android;Linux,NaN,Angular/Angular.js;ASP.NET;Django;jQuery,NaN,.NET;Node.js,Notepad++;PyCharm,Windows,I do not use containers,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,Twitter,In real life (in person),Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat more welcome now than last year,Tech articles written by other developers;Tech...,20.0,Man,No,Straight / Heterosexual,Black or of African descent,No,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86676,87216,I am a student who is learning to code,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",Spain,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,"Designer;Developer, embedded applications or d...",10,14,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",I've never had a job,NaN,NaN,Specific department or team I'd be working on;...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C++;Java;Pyth...,Assembly;Bash/Shell/PowerShell;C;C++;Python;Ot...,MySQL;Oracle;PostgreSQL,NaN,Arduino;Linux;Slack;Windows;WordPress,Arduino;Docker;Linux;Raspberry Pi,NaN,NaN,NaN,NaN,NaN,Linux-based,"Outside of work, for personal projects",NaN,NaN,No,Yes,Yes,Twitter,Online,UserID,2016,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,0-10 minutes,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are",Neutral,A lot less welcome now than last year,Tech articles written by other developers;Tech...,26.0,Woman,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Too long,Easy
87152,87694,I am a student who is learning to code,Yes,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Australia,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,Student,3,12,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,"Languages, frameworks, and other technologies ...",I was preparing for a job search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;Rust;Swift,Bash/Shell/PowerShell;C;Dart;HTML/CSS;Java;Jav...,PostgreSQL,NaN,Android;iOS;MacOS,Android;iOS;Linux;MacOS;Windows,Django,React.js;Ruby on Rails,Node.js,Flutter;Node.js,Android Studio;IntelliJ;Visual Studio Code;Xcode,MacOS,I do not use containers,NaN,NaN,Yes,SIGH,Yes,Twitter,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not at all",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,18.0,Man,No,Gay or Lesbian,South Asian,No,Appropriate in length,Easy
87177,87719,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,Associate degree,Web development or web design,"Taught yourself a new language, framework, or ...",NaN,"Designer;Developer, front-end",6,15,4,Slightly satisfied,NaN,NaN,NaN,NaN,I am actively looking for a job,1-2 years ago,Write any code;Interview with people in peer r...,No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A little above average,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Ruby,HTML/CSS;JavaScript,NaN,NaN,NaN,NaN,Express;jQuery;React.js;Vue.js,React.js;Vue.js,Node.js,Node.js;React Native,Visual Studio Code,MacOS,NaN,NaN,An irresponsible use of resources,No,SIGH,Yes,Twitter,Online,Handle,2012,Less than once per month or monthly,Find answers to specific questions,Less than once per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, I've heard of them, but I am not part of a...","No, not really",Just as welcome now as I felt last year,Courses on technologies you're interested in,27.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy
88140,88690,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",United States,No,I never completed any formal education,NaN,"Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Developer, front-end;Devel...",5,34,5,Very dissatisfied,NaN,NaN,NaN,NaN,I am actively looking for a job,1-2 years ago,Write any code;Complete a take-home project;In...,No,Industry that I'd be working in;Office environ...,Re-entry into the workforce,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Far above average,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;PHP;SQL,NaN,MariaDB;MySQL;SQLite,NaN,MacOS;Slack;WordPress,NaN,jQuery;React.js,Laravel,NaN,Node.js;React Native,Sublime Text,MacOS,I do not use containers,NaN,Useful across many domains and could change ma...,No,Yes,Yes,Twitter,In real life (in person),Username,2013,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Industry news about technologies you're intere...,40.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too long,Easy
88363,7759,NaN,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",Ecuador,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,NaN,"Developer, back-end;Marketing or sales profess...",Less than 1 year,16,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;JavaScript;Python;WebAssembly,NaN,MySQL,NaN,Android;Arduino;AWS;Google Cloud Platform;IBM ...,NaN,Angular/Angular.js;Laravel;React.js;Vue.js,NaN,TensorFlow;Torch/PyTorch;Unity 3D;Unreal Engine,Eclipse;PyCharm,MacOS,I do not use containers,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,Less than once per month or monthly,Find answers to specific questions;Meet other ...,Less than once per week,The other resource was much faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not really",Not applicable - I did not use Stack Overflow ...,Tech meetups or events in your area;Courses on...,38.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,Yes,Appropriate in length,Easy

In [17]:
df.loc[filt2,'Country']

226             France
270             Serbia
282             Canada
515      United States
779              Kenya
             ...
86676            Spain
87152        Australia
87177    United States
88140    United States
88363          Ecuador
Name: Country, Length: 452, dtype: object

In [21]:
high_salary = df['ConvertedComp'] > 70000
df.loc[high_salary,['Country','LanguageWorkedWith','ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
5,Canada,Java;R;SQL,366420.0
8,New Zealand,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,95179.0
12,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0
15,United Kingdom,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,455352.0
21,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
...,...,...,...
88323,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0
88324,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0
88325,United States,HTML/CSS;JavaScript;Scala;TypeScript,130000.0
88326,Finland,Bash/Shell/PowerShell;C++;Python,82488.0
88329,Netherlands,C#;HTML/CSS;Java;JavaScript;PHP;Python,588012.0

In [23]:
countries = ['United States', 'India', 'United Kingdom', 'Germany', 'Canada']
filt3 = df['Country'].isin(countries)
df.loc[filt3,'Country'].value_counts()

United States     20949
India              9061
Germany            5866
United Kingdom     5737
Canada             3395
Name: Country, dtype: int64

In [24]:
filt4 = df['LanguageWorkedWith'].str.contains('Python', na=False)

In [25]:
df.loc[filt4]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
7,8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Engineer, site reliability",8,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...,Cassandra;DynamoDB;Elasticsearch;Firebase;Mong...,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Panda...,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual...,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88854,84539,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"1,000 to 4,999 employees",Academic researcher;Data scientist or machine ...,8,16,6,NaN,NaN,Somewhat confident,No,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;P...,PostgreSQL,NaN,Android;Arduino;Linux;Raspberry Pi,Android;Arduino;Linux,Express;Vue.js,Express;Vue.js,Node.js;TensorFlow,Node.js;TensorFlow,Android Studio;Atom;Eclipse;Vim,Linux-based,I do not use containers,NaN,NaN,Yes,SIGH,Yes,NaN,Online,Username,2011,A few times per week,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Courses on technologies you're interested in,23.0,Woman,Yes,Bisexual,White or of European descent,No,Appropriate in length,Easy
88860,85738,NaN,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Brazil,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,10,5,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C++;Python;Ruby;Other(s):,Assembly;Bash/Shell/PowerShell;C++;Other(s):,NaN,NaN,Linux,Linux,NaN,NaN,TensorFlow;Torch/PyTorch,NaN,Vim,Linux-based,I do not use containers,NaN,Useful across many domains and could change ma...,No,SIGH,Yes,WhatsApp,In real life (in person),Username,2014,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,31-60 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Industry news about technologies you're intere...,15.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Too short,Easy
88865,86566,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Retired,Switzerland,No,Some college/university study without earning ...,"A humanities discipline (ex. literature, histo...",Taken a part-time in-person course in programm...,NaN,NaN,More than 50 years,17,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Python;Other(s):,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Pyth...,NaN,NaN,Linux;Windows,Linux;Windows,NaN,NaN,NaN,NaN,Emacs,Windows,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,SIGH,Yes,YouTube,In real life (in person),Handle,2017,A few times per month or weekly,Find answers to specific questions;Contribute ...,Less than once per week,Stack Overflow was much faster,60+ minutes,Yes,Less than once per month or monthly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,74.0,Man,No,NaN,White or of European descent,No,Appropriate in length,Easy
88872,87739,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Czech Republic,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",500 to 999 employees,"Academic researcher;Designer;Developer, game o...",9,16,3,NaN,NaN,Somewhat confident,No,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;C++;HTML/CSS;JavaScript;PHP;Python;SQL,C++;HTML/CSS;PHP;Python,MySQL,MySQL,Android;Linux;WordPress,Android;Linux,jQuery,jQuery,TensorFlow,NaN,Vim,Linux-based,I do not use containers,NaN,A passing fad,No,Yes,Yes,YouTube,In real life (in person),Login,2009,A few times per month or weekly,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,NaN,25.0,NaN,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
88876,88212,NaN,No,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Spain,No,"Secondary school (e.g. American high school, G...",NaN,"Taught yourself a new language, framework, or ...",10 to 19 employees,"Designer;Developer, front-end;Developer, full-...",18,7,15,NaN,NaN,Somewhat confident,Yes,I am already a manager,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Python,JavaScript,MySQL;PostgreSQL,PostgreSQL,NaN,Arduino,Django;React.js,Django;React.js,NaN,NaN,Atom;Visual Studio Code,MacOS,I do not use containers,Non-currency applications of blockchain,Useful for immutable record keeping outside of...,No,SIGH,No,WhatsApp,In real life (in person),Username,2008,A few times per week,Find answers to specific questions,6-10 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not at all",NaN,Tech articles written by other developers;Indu...,40.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy