In [ ]:
#Different methods to explore/analyze the data in a dataframe

#df['Column_Name'].count() # number of non-null values in the column
#df['Column_name'].value_counts() # number of occurences of each value in the column, basically histogram bins
#df['Column_name'].mean() #mean of the column, will ignore null values
#df['Column_name'].median() #median of the column, will ignore null values
#df['Column_name'].min() #minimum value in the column, will ignore null values
#df['Column_name'].max() #maximum value in the column, will ignore null values
#df.median() #median of all the valid columns in the dataframe, will ignore null values : valid means float or int data type
#df.describe() #summary of all the valid columns in the dataframe, will ignore null values : valid means float or int data typeS
#df['Column_name'].value_counts(normalize=True) #normalzied number of occurences of each value in the column, will ignore null values

# grp = df.groupby(['Column_name']) 
#group the dataframe by the values in the Country column, 
#this will create a group for each unique value in the Country column and will allow us to perform operations on each group separately
#A groupby operation involves some combination of splitting the object, 
#applying a function, and combining the results. 
# This can be used to group large amounts of data and compute operations on these groups.
#grp.get_group('Country_Name').describe() #will describe the group of rows where the value in the Country column is Country_NameS





import pandas as pd
inpFilePath ='/Users/sam/git/Pandas_Data/Input/Data_2019/'
df = pd.read_csv(inpFilePath + 'survey_results_public.csv')
schema_df = pd.read_csv(inpFilePath + 'survey_results_schema.csv')
pd.set_option('display.max_columns', 85) #to display all columns in the dataframe
pd.set_option('display.max_rows', 85)   #to see all rows in the dataframe of schema
pd.set_option('display.width', 100)    #to set the width of the display to 1000 characters

people = {
    "first": ["Corey", "Jane", "John","Adam"],
    "last": ["Schafer", "Doe", "Doe","Doe"],
    "email": ["Corey.Schafer@gmail.com", "Jane.Doe@gmail.com", "John.Smith@gmail.com","Adam.Doe@gmail.com"]
}
df1 = pd.DataFrame(people)

In [2]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [3]:
df['ConvertedComp'].count() # number of non-null values in the column

55823

In [4]:
df['ConvertedComp'].value_counts() # number of occurences of each value in the column, basically histogram bins

2000000.0    709
1000000.0    558
120000.0     502
100000.0     480
150000.0     434
            ...
52826.0        1
72888.0        1
7548.0         1
20436.0        1
44947.0        1
Name: ConvertedComp, Length: 9162, dtype: int64

In [14]:
df['ConvertedComp'].head(15)

0          NaN
1          NaN
2       8820.0
3      61000.0
4          NaN
5     366420.0
6          NaN
7          NaN
8      95179.0
9      13293.0
10         NaN
11         NaN
12     90000.0
13     57060.0
14         NaN
Name: ConvertedComp, dtype: float64

In [ ]:
df['ConvertedComp'].mean() #mean of the column, will ignore null values

127110.73842323056

In [6]:
df['ConvertedComp'].median()

57287.0

In [18]:
df.median()

Respondent       44442.0
CompTotal        62000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [7]:
df.describe()

         Respondent     CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  88883.000000  5.594500e+04   5.582300e+04  64503.000000  49790.000000  79210.000000
mean   44442.000000  5.519014e+11   1.271107e+05     42.127197      5.084308     30.336699
std    25658.456325  7.331926e+13   2.841523e+05     37.287610      5.513931      9.178390
min        1.000000  0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    22221.500000  2.000000e+04   2.577750e+04     40.000000      2.000000     24.000000
50%    44442.000000  6.200000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    66662.500000  1.200000e+05   1.000000e+05     44.750000      6.000000     35.000000
max    88883.000000  1.000000e+16   2.000000e+06   4850.000000     99.000000     99.000000

In [8]:
df['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [9]:
df['SocialMedia'].value_counts()

Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: SocialMedia, dtype: int64

In [16]:
schema_df

                    Column                                       QuestionText
0               Respondent  Randomized respondent ID number (not in order ...
1               MainBranch  Which of the following options best describes ...
2                 Hobbyist                            Do you code as a hobby?
3              OpenSourcer        How often do you contribute to open source?
4               OpenSource  How do you feel about the quality of open sour...
5               Employment  Which of the following best describes your cur...
6                  Country          In which country do you currently reside?
7                  Student  Are you currently enrolled in a formal, degree...
8                  EdLevel  Which of the following best describes the high...
9           UndergradMajor  What was your main or most important field of ...
10                EduOther  Which of the following types of non-degree edu...
11                 OrgSize  Approximately how many people are employed by ...
12                 DevType  Which of the following describe you? Please se...
13               YearsCode  Including any education, how many years have y...
14              Age1stCode  At what age did you write your first line of c...
15            YearsCodePro  How many years have you coded professionally (...
16               CareerSat  Overall, how satisfied are you with your caree...
17                  JobSat  How satisfied are you with your current job? (...
18                MgrIdiot  How confident are you that your manager knows ...
19                MgrMoney  Do you believe that you need to be a manager t...
20                 MgrWant  Do you want to become a manager yourself in th...
21                 JobSeek  Which of the following best describes your cur...
22            LastHireDate  When was the last time that you took a job wit...
23                 LastInt  In your most recent successful job interview (...
24                FizzBuzz  Have you ever been asked to solve FizzBuzz in ...
25              JobFactors  Imagine that you are deciding between two job ...
26            ResumeUpdate  Think back to the last time you updated your r...
27          CurrencySymbol  Which currency do you use day-to-day? If your ...
28            CurrencyDesc  Which currency do you use day-to-day? If your ...
29               CompTotal  What is your current total compensation (salar...
30                CompFreq   Is that compensation weekly, monthly, or yearly?
31           ConvertedComp  Salary converted to annual USD salaries using ...
32             WorkWeekHrs   On average, how many hours per week do you work?
33                WorkPlan            How structured or planned is your work?
34           WorkChallenge  Of these options, what are your greatest chall...
35              WorkRemote                    How often do you work remotely?
36                 WorkLoc                    Where would you prefer to work?
37                  ImpSyn  For the specific work you do, and the years of...
38                 CodeRev           Do you review code as part of your work?
39              CodeRevHrs  On average, how many hours per week do you spe...
40               UnitTests  Does your company regularly employ unit tests ...
41             PurchaseHow  How does your company make decisions about pur...
42            PurchaseWhat  What level of influence do you, personally, ha...
43      LanguageWorkedWith  Which of the following programming, scripting,...
44  LanguageDesireNextYear  Which of the following programming, scripting,...
45      DatabaseWorkedWith  Which of the following database environments h...
46  DatabaseDesireNextYear  Which of the following database environments h...
47      PlatformWorkedWith  Which of the following platforms have you done...
48  PlatformDesireNextYear  Which of the following platforms have you done...
49      WebFrameWorkedWith  Which of the following web frameworks have you...
50  WebFrameDesireNextYear  Which of the following web frameworks have you...
51      MiscTechWorkedWith  Which of the following other frameworks, libra...
52  MiscTechDesireNextYear  Which of the following other frameworks, libra...
53              DevEnviron  Which development environment(s) do you use re...
54                   OpSys  What is the primary operating system in which ...
55              Containers  How do you use containers (Docker, Open Contai...
56           BlockchainOrg  How is your organization thinking about or imp...
57            BlockchainIs  Blockchain / cryptocurrency technology is prim...
58              BetterLife  Do you think people born today will have a bet...
59                ITperson   Are you the "IT support person" for your family?
60                   OffOn        Have you tried turning it off and on again?
61             SocialMedia        What social media site do you use the most?
62            Extraversion    Do you prefer online chat or IRL conversations?
63              ScreenName                               What do you call it?
64              SOVisit1st  To the best of your memory, when did you first...
65             SOVisitFreq  How frequently would you say you visit Stack O...
66               SOVisitTo  I visit Stack Overflow to... (check all that a...
67            SOFindAnswer  On average, how many times a week do you find ...
68             SOTimeSaved  Think back to the last time you solved a codin...
69           SOHowMuchTime  About how much time did you save? If you're no...
70               SOAccount              Do you have a Stack Overflow account?
71              SOPartFreq  How frequently would you say you participate i...
72                  SOJobs  Have you ever used or visited Stack Overflow J...
73                EntTeams  Have you ever used Stack Overflow for Enterpri...
74                  SOComm  Do you consider yourself a member of the Stack...
75           WelcomeChange  Compared to last year, how welcome do you feel...
76            SONewContent  Would you like to see any of the following on ...
77                     Age  What is your age (in years)? If you prefer not...
78                  Gender  Which of the following do you currently identi...
79                   Trans                    Do you identify as transgender?
80               Sexuality  Which of the following do you currently identi...
81               Ethnicity  Which of the following do you identify as? Ple...
82              Dependents  Do you have any dependents (e.g., children, el...
83            SurveyLength  How do you feel about the length of the survey...
84              SurveyEase  How easy or difficult was this survey to compl...

In [14]:
schema_df['Column']

0                 Respondent
1                 MainBranch
2                   Hobbyist
3                OpenSourcer
4                 OpenSource
5                 Employment
6                    Country
7                    Student
8                    EdLevel
9             UndergradMajor
10                  EduOther
11                   OrgSize
12                   DevType
13                 YearsCode
14                Age1stCode
15              YearsCodePro
16                 CareerSat
17                    JobSat
18                  MgrIdiot
19                  MgrMoney
20                   MgrWant
21                   JobSeek
22              LastHireDate
23                   LastInt
24                  FizzBuzz
25                JobFactors
26              ResumeUpdate
27            CurrencySymbol
28              CurrencyDesc
29                 CompTotal
30                  CompFreq
31             ConvertedComp
32               WorkWeekHrs
33                  WorkPlan
34             WorkChallenge
35                WorkRemote
36                   WorkLoc
37                    ImpSyn
38                   CodeRev
39                CodeRevHrs
40                 UnitTests
41               PurchaseHow
42              PurchaseWhat
43        LanguageWorkedWith
44    LanguageDesireNextYear
45        DatabaseWorkedWith
46    DatabaseDesireNextYear
47        PlatformWorkedWith
48    PlatformDesireNextYear
49        WebFrameWorkedWith
50    WebFrameDesireNextYear
51        MiscTechWorkedWith
52    MiscTechDesireNextYear
53                DevEnviron
54                     OpSys
55                Containers
56             BlockchainOrg
57              BlockchainIs
58                BetterLife
59                  ITperson
60                     OffOn
61               SocialMedia
62              Extraversion
63                ScreenName
64                SOVisit1st
65               SOVisitFreq
66                 SOVisitTo
67              SOFindAnswer
68               SOTimeSaved
69             SOHowMuchTime
70                 SOAccount
71                SOPartFreq
72                    SOJobs
73                  EntTeams
74                    SOComm
75             WelcomeChange
76              SONewContent
77                       Age
78                    Gender
79                     Trans
80                 Sexuality
81                 Ethnicity
82                Dependents
83              SurveyLength
84                SurveyEase
Name: Column, dtype: object

In [17]:
schema_df[schema_df['Column'] =='SocialMedia'] 
#what is the value of the row where the column name is SocialMedia in the schema dataframe

         Column                                 QuestionText
61  SocialMedia  What social media site do you use the most?

In [33]:
df['SocialMedia'].value_counts(normalize=True)

Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: SocialMedia, dtype: float64

In [18]:
df['Country'].value_counts()

United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
                                    ...
Sao Tome and Principe                   1
Dominica                                1
Papua New Guinea                        1
Brunei Darussalam                       1
Saint Vincent and the Grenadines        1
Name: Country, Length: 179, dtype: int64

In [20]:
df.groupby(['Country'])
#group the dataframe by the values in the Country column, 
# this will create a group for each unique value in the Country column 
# and will allow us to perform operations on each group separately

In [24]:
Countrygrp = df.groupby(['Country'])

In [ ]:
Countrygrp.describe()
#Information about each unique value in the Country column,
#Is described here for all valid columns in the dataframe, will ignore null values : valid columns means  those columns with float or int data type

                                     Respondent                                                 \
                                          count          mean           std      min       25%
Country
Afghanistan                                44.0  47441.431818  26547.217894    722.0  28943.25
Albania                                    86.0  41695.546512  24199.484198   1954.0  19187.25
Algeria                                   134.0  43010.126866  25308.029814   1102.0  22301.75
Andorra                                     7.0  50079.857143  33627.941940   1547.0  28684.50
Angola                                      5.0  50569.400000  28639.499460   8172.0  46837.00
...                                         ...           ...           ...      ...       ...
Venezuela, Bolivarian Republic of...       88.0  43461.170455  25866.546647   1438.0  19100.75
Viet Nam                                  231.0  43895.337662  24367.137680    161.0  24468.00
Yemen                                      19.0  45331.157895  29720.785671   1129.0  16837.50
Zambia                                     12.0  42096.833333  21487.596443  11557.0  27748.75
Zimbabwe                                   39.0  37455.410256  26951.682747    251.0  14345.50

                                                                 CompTotal                \
                                          50%       75%      max     count          mean
Country
Afghanistan                           49069.0  62648.50  88731.0      12.0  5.418654e+07
Albania                               39968.0  62843.75  85878.0      50.0  1.707424e+05
Algeria                               41281.0  64722.25  88186.0      43.0  7.544398e+04
Andorra                               51904.0  78312.00  83115.0       2.0  7.650000e+04
Angola                                50294.0  59761.00  87783.0       1.0  2.020000e+05
...                                       ...       ...      ...       ...           ...
Venezuela, Bolivarian Republic of...  42945.0  66726.00  87213.0      43.0  1.174443e+05
Viet Nam                              45254.0  64572.00  88682.0      88.0  2.613438e+07
Yemen                                 47528.0  66422.50  88559.0       6.0  1.375000e+05
Zambia                                38160.5  62943.75  73166.0       8.0  2.774375e+04
Zimbabwe                              32960.0  56649.50  84155.0      15.0  7.841667e+03

                                                                                                \
                                               std       min       25%         50%         75%
Country
Afghanistan                           1.872670e+08       1.0    9250.0     39000.0    112500.0
Albania                               4.623662e+05     400.0    2625.0     65000.0     89300.0
Algeria                               7.478817e+04       0.0   32500.0     55000.0     97500.0
Andorra                               1.039447e+05    3000.0   39750.0     76500.0    113250.0
Angola                                         NaN  202000.0  202000.0    202000.0    202000.0
...                                            ...       ...       ...         ...         ...
Venezuela, Bolivarian Republic of...  4.889418e+05       0.0     350.0      1000.0     18000.0
Viet Nam                              5.156000e+07       0.0  950000.0  15000000.0  27884500.0
Yemen                                 1.183110e+05    5000.0   50000.0    125000.0    215000.0
Zambia                                5.153904e+04     100.0    2087.5      5000.0     21000.0
Zimbabwe                              1.785694e+04      75.0     950.0      1600.0      3000.0

                                                  ConvertedComp                                \
                                              max         count           mean            std
Country
Afghanistan                           648838511.0          12.0  101953.333333  285995.241798
Albania                                 2688000.0          50.0   21833.700000   31450.766680
Algeria                                  300000.0          42.0   34924.047619  152933.628015
Andorra                                  150000.0           2.0  160931.000000   15458.768450
Angola                                   202000.0           1.0    7764.000000            NaN
...                                           ...           ...            ...            ...
Venezuela, Bolivarian Republic of...    3000000.0          43.0   14581.627907   24218.759814
Viet Nam                              365000000.0          87.0   17233.436782   19921.575978
Yemen                                    300000.0           6.0   16909.166667   21847.429143
Zambia                                   150000.0           8.0   10075.375000   13200.366434
Zimbabwe                                  70000.0          15.0   34046.666667   44166.969990

                                                                                          \
                                           min       25%       50%        75%        max
Country
Afghanistan                                0.0    1476.0    6222.0   17955.00  1000000.0
Albania                                 1320.0    7314.0   10818.0   23052.00   187668.0
Algeria                                    0.0    4701.0    7878.0   14391.00  1000000.0
Andorra                               150000.0  155465.5  160931.0  166396.50   171862.0
Angola                                  7764.0    7764.0    7764.0    7764.00     7764.0
...                                        ...       ...       ...        ...        ...
Venezuela, Bolivarian Republic of...       0.0    1950.0    6384.0   18000.00   137484.0
Viet Nam                                 200.0    7236.0   11892.0   18000.00   140000.0
Yemen                                    799.0    4437.0   11940.0   14115.00    60000.0
Zambia                                   400.0    2103.0    5040.0   12734.25    40524.0
Zimbabwe                                 900.0   12000.0   19200.0   36000.00   180000.0

                                     WorkWeekHrs                                                  \
                                           count       mean        std   min    25%   50%    75%
Country
Afghanistan                                 17.0  55.352941  46.731870   1.0  36.00  45.0  50.00
Albania                                     66.0  40.121212  10.976219   8.0  40.00  40.0  44.25
Algeria                                     43.0  38.220930  24.150397   6.0  32.50  40.0  40.00
Andorra                                      2.0  42.000000   2.828427  40.0  41.00  42.0  43.00
Angola                                       1.0  45.000000        NaN  45.0  45.00  45.0  45.00
...                                          ...        ...        ...   ...    ...   ...    ...
Venezuela, Bolivarian Republic of...        54.0  40.444444  27.974831   3.0  30.00  40.0  40.00
Viet Nam                                   112.0  44.602679  22.772785   8.0  40.00  40.0  44.00
Yemen                                        8.0  41.250000  28.848124   7.0  20.75  40.0  55.00
Zambia                                       8.0  48.125000  13.076014  40.0  40.00  40.0  52.50
Zimbabwe                                    18.0  43.666667  23.659347   7.0  40.00  46.5  58.50

                                            CodeRevHrs                                           \
                                        max      count       mean        std   min    25%   50%
Country
Afghanistan                           168.0       16.0  14.062500  21.726999   1.0   5.00   8.0
Albania                                65.0       55.0   5.781818   3.842698   1.0   3.00   5.0
Algeria                               168.0       29.0   6.413793   5.729106   1.0   3.00   4.0
Andorra                                44.0        2.0   2.500000   0.707107   2.0   2.25   2.5
Angola                                 45.0        1.0  10.000000        NaN  10.0  10.00  10.0
...                                     ...        ...        ...        ...   ...    ...   ...
Venezuela, Bolivarian Republic of...  160.0       39.0   6.717949   8.347545   1.0   3.00   5.0
Viet Nam                              168.0      103.0   8.407767  11.150650   0.5   4.00   5.0
Yemen                                  90.0        5.0  12.800000  18.308468   1.0   3.00   5.0
Zambia                                 75.0        5.0  18.400000  15.662056   5.0   7.00  10.0
Zimbabwe                               96.0       11.0  10.636364   6.233341   2.0   5.00  10.0

                                                     Age                                           \
                                        75%   max  count       mean        std   min    25%   50%
Country
Afghanistan                           10.50  90.0   23.0  27.913043  15.776602   1.0  23.50  25.0
Albania                                7.50  20.0   72.0  25.145833   5.104153  15.0  22.00  24.0
Algeria                               10.00  20.0  109.0  27.284404   8.684908   5.0  22.00  25.0
Andorra                                2.75   3.0    4.0  28.000000  14.764823  19.0  19.75  21.5
Angola                                10.00  10.0    3.0  26.666667   7.234178  22.0  22.50  23.0
...                                     ...   ...    ...        ...        ...   ...    ...   ...
Venezuela, Bolivarian Republic of...   7.00  50.0   83.0  28.301205  10.128124  17.0  22.00  25.0
Viet Nam                               9.00  99.0  173.0  26.739884   9.991652   1.0  22.00  25.0
Yemen                                 10.00  45.0   17.0  28.117647   5.011017  22.0  25.00  27.0
Zambia                                30.00  40.0   11.0  28.000000   7.962412  19.0  23.00  26.0
Zimbabwe                              15.00  20.0   35.0  27.371429   5.557643  20.0  24.00  26.0


                                        75%   max
Country
Afghanistan                           26.00  85.0
Albania                               27.00  40.0
Algeria                               30.00  63.0
Andorra                               29.75  50.0
Angola                                29.00  35.0
...                                     ...   ...
Venezuela, Bolivarian Republic of...  31.50  61.0
Viet Nam                              29.00  99.0
Yemen                                 32.00  39.0
Zambia                                29.00  49.0
Zimbabwe                              29.50  46.0

[179 rows x 48 columns]

In [30]:
Countrygrp.get_group('India').describe()

         Respondent     CompTotal  ConvertedComp  WorkWeekHrs   CodeRevHrs          Age
count   9061.000000  4.017000e+03   3.999000e+03  5571.000000  5058.000000  7307.000000
mean   44477.174043  5.061513e+07   2.805766e+04    42.203159     7.297837    25.927439
std    25514.630987  3.155567e+09   8.563000e+04    66.273189     8.185413     5.443127
min        8.000000  0.000000e+00   0.000000e+00     2.000000     0.000000     1.000000
25%    22303.000000  4.000000e+04   5.040000e+03    40.000000     3.000000    22.000000
50%    44494.000000  4.050000e+05   1.008000e+04    42.000000     5.000000    25.000000
75%    66294.000000  1.100000e+06   2.098900e+04    48.000000    10.000000    28.000000
max    88872.000000  2.000000e+11   2.000000e+06  4850.000000    99.000000    98.000000

In [ ]:
#another way to do is using filt and loc based selection
filt1 = df['Country'] == 'India'
df.loc[filt1].describe()

         Respondent     CompTotal  ConvertedComp  WorkWeekHrs   CodeRevHrs          Age
count   9061.000000  4.017000e+03   3.999000e+03  5571.000000  5058.000000  7307.000000
mean   44477.174043  5.061513e+07   2.805766e+04    42.203159     7.297837    25.927439
std    25514.630987  3.155567e+09   8.563000e+04    66.273189     8.185413     5.443127
min        8.000000  0.000000e+00   0.000000e+00     2.000000     0.000000     1.000000
25%    22303.000000  4.000000e+04   5.040000e+03    40.000000     3.000000    22.000000
50%    44494.000000  4.050000e+05   1.008000e+04    42.000000     5.000000    25.000000
75%    66294.000000  1.100000e+06   2.098900e+04    48.000000    10.000000    28.000000
max    88872.000000  2.000000e+11   2.000000e+06  4850.000000    99.000000    98.000000

In [32]:
Countrygrp['SocialMedia'].value_counts().head(50)

Country              SocialMedia
Afghanistan          Facebook                     15
                     YouTube                       9
                     I don't use social media      6
                     WhatsApp                      4
                     Instagram                     1
                     LinkedIn                      1
                     Twitter                       1
Albania              WhatsApp                     18
                     Facebook                     16
                     Instagram                    13
                     YouTube                      10
                     Twitter                       8
                     LinkedIn                      7
                     Reddit                        6
                     I don't use social media      4
                     Snapchat                      1
                     WeChat 微信                     1
Algeria              YouTube                      42
                     Facebook                     41
                     Twitter                      14
                     LinkedIn                      9
                     I don't use social media      7
                     Instagram                     7
                     Reddit                        2
                     WhatsApp                      2
Andorra              Facebook                      2
                     I don't use social media      2
                     Reddit                        1
                     Snapchat                      1
                     YouTube                       1
Angola               Twitter                       2
                     Facebook                      1
                     YouTube                       1
Antigua and Barbuda  YouTube                       2
                     Facebook                      1
                     Instagram                     1
                     Twitter                       1
                     VK ВКонта́кте                 1
Argentina            WhatsApp                    202
                     Twitter                      80
                     YouTube                      62
                     Instagram                    53
                     Reddit                       50
                     Facebook                     45
                     I don't use social media     22
                     LinkedIn                     16
Armenia              Facebook                     38
                     YouTube                      23
                     LinkedIn                      5
                     Instagram                     3
Name: SocialMedia, dtype: int64

In [33]:
Countrygrp['SocialMedia'].value_counts().loc['Russian Federation']

SocialMedia
VK ВКонта́кте               442
YouTube                     302
I don't use social media    155
Reddit                      140
Twitter                     130
Instagram                    94
WhatsApp                     90
Facebook                     67
LinkedIn                     35
Snapchat                      1
Name: SocialMedia, dtype: int64

In [34]:
Countrygrp['ConvertedComp'].median().loc['Germany']

63016.0

In [35]:
Countrygrp['ConvertedComp'].agg(['median','mean'])

                                        median           mean
Country
Afghanistan                             6222.0  101953.333333
Albania                                10818.0   21833.700000
Algeria                                 7878.0   34924.047619
Andorra                               160931.0  160931.000000
Angola                                  7764.0    7764.000000
...                                        ...            ...
Venezuela, Bolivarian Republic of...    6384.0   14581.627907
Viet Nam                               11892.0   17233.436782
Yemen                                  11940.0   16909.166667
Zambia                                  5040.0   10075.375000
Zimbabwe                               19200.0   34046.666667

[179 rows x 2 columns]

In [36]:
Countrygrp['ConvertedComp'].agg(['median','mean']).loc['United States']

median    110000.000000
mean      249546.254589
Name: United States, dtype: float64

In [37]:
filt1 = df['Country'] == 'India'
df.loc[filt1]['LanguageWorkedWith']

7        Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
9                            C#;Go;JavaScript;Python;R;SQL
14       Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...
49       Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
64                         Assembly;C;C++;C#;HTML/CSS;Java
                               ...
88808                                            Other(s):
88825                 Bash/Shell/PowerShell;Python;SQL;VBA
88852    Assembly;C;C++;HTML/CSS;Java;JavaScript;Object...
88853     HTML/CSS;Java;JavaScript;Python;Swift;TypeScript
88864        Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript
Name: LanguageWorkedWith, Length: 9061, dtype: object

In [38]:
filt1 = df['Country'] == 'India'
df.loc[filt1]['LanguageWorkedWith'].str.contains('Python')

7         True
9         True
14       False
49        True
64       False
         ...
88808    False
88825     True
88852    False
88853     True
88864    False
Name: LanguageWorkedWith, Length: 9061, dtype: object

In [39]:
filt1 = df['Country'] == 'India'
df.loc[filt1]['LanguageWorkedWith'].str.contains('Python').value_counts()

False    5739
True     3105
Name: LanguageWorkedWith, dtype: int64

In [ ]:

'''
Countrygrp['LanguageWorkedWith'].str.contains('Python').sum()S
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-62-b0e25984d7ed> in <module>
----> 1 Countrygrp['LanguageWorkedWith'].str.contains('Python').sum()

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/groupby/groupby.py in __getattr__(self, attr)
    701             return self[attr]
    702 
--> 703         raise AttributeError(
    704             f"'{type(self).__name__}' object has no attribute '{attr}'"
    705         )

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

'''

In [64]:
Countrygrp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').value_counts(normalize=True))

Country
Afghanistan  False    0.794872
             True     0.205128
Albania      False    0.722892
             True     0.277108
Algeria      False    0.682540
                        ...
Yemen        True     0.176471
Zambia       False    0.666667
             True     0.333333
Zimbabwe     False    0.641026
             True     0.358974
Name: LanguageWorkedWith, Length: 335, dtype: float64