In [43]:
import pandas as pd
inpFilePath ='/Users/sam/git/Pandas_Data/Input/Data_2019/'

inpFilePath='/Users/sam/git/Pandas_Data/Input/Data_2019/'

df = pd.read_csv(inpFilePath + 'survey_results_public.csv')
schema_df = pd.read_csv(inpFilePath + 'survey_results_schema.csv')
pd.set_option('display.max_columns', 85) #to display all columns in the dataframe
pd.set_option('display.max_rows', 85)   #to see all rows in the dataframe of schema
pd.set_option('display.width', 1000)    #to set the width of the display to 1000 characters

In [44]:
people = {
    "first": ["Corey", "Jane", "John"],
    "last": ["Schafer", "Doe", "Smith"],
    "email": ["Corey.Schafer@gmail.com", "Jane.Doe@gmail.com", "John.Smith@gmail.com"]
}
df1 = pd.DataFrame(people)
df1

   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John    Smith     John.Smith@gmail.com

In [45]:
df1.columns

Index(['first', 'last', 'email'], dtype='object')

In [46]:
df1.columns.shape

(3,)

In [47]:
df1.columns[0:2] # 2 is exclusive, so it will give us the first two columns

Index(['first', 'last'], dtype='object')

In [48]:
df1['first']

0    Corey
1     Jane
2     John
Name: first, dtype: object

In [49]:
df1['first'].shape

(3,)

In [50]:
df1['first']+df1['last']
#will add first and last name together 
# but there is no space in between.

0    CoreySchafer
1         JaneDoe
2       JohnSmith
dtype: object

In [51]:
# To add space we can do this
df1['first'] + ' ' + df1['last']

0    Corey Schafer
1         Jane Doe
2       John Smith
dtype: object

In [52]:
df1['full_name'] = df1['first'] + ' ' + df1['last']
df1

   first     last                    email      full_name
0  Corey  Schafer  Corey.Schafer@gmail.com  Corey Schafer
1   Jane      Doe       Jane.Doe@gmail.com       Jane Doe
2   John    Smith     John.Smith@gmail.com     John Smith

In [53]:
df1.drop(columns = ['first','last'],inplace=True) #drop method is used to drop the clumns
df1

                     email      full_name
0  Corey.Schafer@gmail.com  Corey Schafer
1       Jane.Doe@gmail.com       Jane Doe
2     John.Smith@gmail.com     John Smith

In [54]:
df1['full_name'].str.split(' ',expand=True) 
#expand = True will give us a dataframe with two columns, one for first name and one for last name.
#The split is done on the space character, so it will split the full name into first and last name.

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John    Smith

In [55]:
df1[['first','last']] = df1['full_name'].str.split(' ',expand=True)

In [56]:
df1

                     email      full_name  first     last
0  Corey.Schafer@gmail.com  Corey Schafer  Corey  Schafer
1       Jane.Doe@gmail.com       Jane Doe   Jane      Doe
2     John.Smith@gmail.com     John Smith   John    Smith

In [57]:
#df1.append({'first':'Tony'})
#gives error we need to specify ignore_index = True to avoid error.
df1.append({'first':'Tony'},ignore_index=True)
#ignore_index will give us a new index for the new row that we are adding.
#this will not update the original dataframe, it will return a new dataframe with the new row added.S

                     email      full_name  first     last
0  Corey.Schafer@gmail.com  Corey Schafer  Corey  Schafer
1       Jane.Doe@gmail.com       Jane Doe   Jane      Doe
2     John.Smith@gmail.com     John Smith   John    Smith
3                      NaN            NaN   Tony      NaN

In [58]:
people = {
    "first": ["Tony", "Steve"],
    "last": ["Stark", "Rogers"],
    "email": ["Ironman@avenge.com", "Cap@avenege.com"]
}
df2 = pd.DataFrame(people) #will read dictionary and create a dataframe
df2

   first    last               email
0   Tony   Stark  Ironman@avenge.com
1  Steve  Rogers     Cap@avenege.com

In [59]:
df1

                     email      full_name  first     last
0  Corey.Schafer@gmail.com  Corey Schafer  Corey  Schafer
1       Jane.Doe@gmail.com       Jane Doe   Jane      Doe
2     John.Smith@gmail.com     John Smith   John    Smith

In [60]:
df1 = df1.append(df2,ignore_index=True)
df1

                     email      full_name  first     last
0  Corey.Schafer@gmail.com  Corey Schafer  Corey  Schafer
1       Jane.Doe@gmail.com       Jane Doe   Jane      Doe
2     John.Smith@gmail.com     John Smith   John    Smith
3       Ironman@avenge.com            NaN   Tony    Stark
4          Cap@avenege.com            NaN  Steve   Rogers

In [61]:
df1.drop(index =4,inplace=True)
df1

                     email      full_name  first     last
0  Corey.Schafer@gmail.com  Corey Schafer  Corey  Schafer
1       Jane.Doe@gmail.com       Jane Doe   Jane      Doe
2     John.Smith@gmail.com     John Smith   John    Smith
3       Ironman@avenge.com            NaN   Tony    Stark

In [62]:
df1['last']

0    Schafer
1        Doe
2      Smith
3      Stark
Name: last, dtype: object

In [63]:
df1['last'] == 'Stark'

0    False
1    False
2    False
3     True
Name: last, dtype: bool

In [64]:
filt = df1['last'] == 'Stark'
df1[filt]

                email full_name first   last
3  Ironman@avenge.com       NaN  Tony  Stark

In [65]:

df1[filt].index

Int64Index([3], dtype='int64')

In [66]:
df1 = df1.drop(index=df1[filt].index)
df1

                     email      full_name  first     last
0  Corey.Schafer@gmail.com  Corey Schafer  Corey  Schafer
1       Jane.Doe@gmail.com       Jane Doe   Jane      Doe
2     John.Smith@gmail.com     John Smith   John    Smith