In [36]:
import pandas as pd

In [37]:
pwd

'/Users/sam/git/Pandas'

In [38]:
ls -tlrh

total 4712
-rw-r--r--@ 1 sam  staff   227K Mar 31 12:48 Lession3_Pandas.ipynb
-rw-r--r--@ 1 sam  staff   499K Apr  1 23:03 Lession4_Pandas_Filter.ipynb
-rw-r--r--@ 1 sam  staff   124K Apr  3 19:20 Lession5_Pandas_Update_Rows_Cols.ipynb
-rw-r--r--@ 1 sam  staff    30K Apr  3 22:43 Lession6_Pandas_Update_Rows_Col.ipynb
-rw-r--r--@ 1 sam  staff   237K Apr  4 13:10 Lession7_Pandas_Sortinh.ipynb
-rw-r--r--@ 1 sam  staff    81K Apr  5 19:26 Lession8_Explore_Analyze_Data.ipynb
-rw-r--r--@ 1 sam  staff   122K Apr 10 22:49 Lession10_Pandas_Dates_Times.ipynb
-rw-r--r--@ 1 sam  staff   194K Apr 11 11:05 Lession11_Pandas_File_Handling.ipynb
-rw-r--r--@ 1 sam  staff   192K Apr 11 16:32 Lession9_Cleaning_Data.ipynb
-rw-r--r--@ 1 sam  staff   433K Apr 11 17:17 Lession1_Pandas.ipynb
-rw-r--r--@ 1 sam  staff   190K Apr 11 17:57 Lession2_Pandas.ipynb

In [39]:
inpFilePath ='/Users/sam/git/Pandas_Data/Input/Data_2019/'
df = pd.read_csv(inpFilePath+'survey_results_public.csv')
schema_df = pd.read_csv(inpFilePath+'survey_results_schema.csv')
pd.set_option('display.max_columns', 85) #to display all columns in the dataframe
pd.set_option('display.max_rows', 85)   #to see all rows in the dataframe of schema
pd.set_option('max_colwidth', 100) #to see the 1000 chars column width of the dataframe of schema

#Just for Understanding: 
#In dictioneries a single key has single value
#but in DataFrame a single key can have multiple values 
#i.e. values are stored in list


'''

#Standard Definition of Dictionary
Sample_Dict ={
    "First": "Sam",
    "Last": "Thakur",
    "Age": "34"
}


#Making All of Values in Dictionary as List
Sample_Dict ={
    "First": ["Sam"],
    "Last": ["Thakur"],
    "Age": ["34"]
}

#Making All of Values in Dictionary as List of Multiple Values
Sample_Dict ={
    "First": ["Sam","Archna","Anaysha"],
    "Last": ["Thakur","Puri","Thakur],
    "Age": ["34","33","1"]
}



'''

'\n\n#Standard Definition of Dictionary\nSample_Dict ={\n    "First": "Sam",\n    "Last": "Thakur",\n    "Age": "34"\n}\n\n\n#Making All of Values in Dictionary as List\nSample_Dict ={\n    "First": ["Sam"],\n    "Last": ["Thakur"],\n    "Age": ["34"]\n}\n\n#Making All of Values in Dictionary as List of Multiple Values\nSample_Dict ={\n    "First": ["Sam","Archna","Anaysha"],\n    "Last": ["Thakur","Puri","Thakur],\n    "Age": ["34","33","1"]\n}\n\n\n\n'

In [40]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software is about the same,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or tool without taking a formal course",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a job board","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software is about the same,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",NaN,Taken an online course in programming or software development (e.g. a MOOC),NaN,"Developer, desktop or enterprise applications;Developer, front-end",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the company or organization;Specific department or te...,"Something else changed (education, award, media, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change many aspects of our lives,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Designer;Developer, back-end;Developer, front-end;Developer, full-stack",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new opportunities",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies I'd be working with;Remote work options;Flex time ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what seems most important or urgent,Distracting work environment;Inadequate access to necessary tools;Lack of support from management,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software is about the same,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job ...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Interview with people in senior / management roles",No,"Languages, frameworks, and other technologies I'd be working with;Office environment or company ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what seems most important or urgent,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence on purchasing new technology,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the time / relax,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job ...,"10,000 or more employees","Academic researcher;Developer, desktop or enterprise applications;Developer, full-stack;Develope...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a whiteboard);Solve a brain-teaser style puzzle;Inte...",No,"Industry that I'd be working in;Languages, frameworks, and other technologies I'd be working wit...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",Being tasked with non-development work;Inadequate access to necessary tools;Non-work commitments...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [41]:
schema_df.head()

,Column,QuestionText
0,Respondent,Randomized respondent ID number (not in order of survey response time)
1,MainBranch,"Which of the following options best describes you today? Here, by ""developer"" we mean ""someone w..."
2,Hobbyist,Do you code as a hobby?
3,OpenSourcer,How often do you contribute to open source?
4,OpenSource,How do you feel about the quality of open source software (OSS)?

In [42]:
df['MainBranch']

0                                               I am a student who is learning to code
1                                               I am a student who is learning to code
2        I am not primarily a developer, but I write code sometimes as part of my work
3                                                       I am a developer by profession
4                                                       I am a developer by profession
                                             ...
88878                                                                              NaN
88879                                                                              NaN
88880                                                                              NaN
88881                                                                              NaN
88882                                                                              NaN
Name: MainBranch, Length: 88883, dtype: object

In [43]:
type(df['MainBranch'])
#pandas.core.series.Series
# Series object is a row of single column of data in a dataframe
# Data Frame is container for multiple series objetcs

pandas.core.series.Series

In [44]:
df.MainBranch
#same as df['MainBranch']
#but better to use df['MainBranch'] becuase one of the name of columns of df can be same as methods/attributes of df 
# e.g. sometimes df.count will access count method in df rather than column

0                                               I am a student who is learning to code
1                                               I am a student who is learning to code
2        I am not primarily a developer, but I write code sometimes as part of my work
3                                                       I am a developer by profession
4                                                       I am a developer by profession
                                             ...
88878                                                                              NaN
88879                                                                              NaN
88880                                                                              NaN
88881                                                                              NaN
88882                                                                              NaN
Name: MainBranch, Length: 88883, dtype: object

In [45]:
df[['MainBranch','Hobbyist']] 
#List of Columns to access multiple columns of dataframe
# if only given single brancket python will think name of column is " MainBranch','Hobbyist " 
#Multiple columns giving another sub dataframe not series now

,MainBranch,Hobbyist
0,I am a student who is learning to code,Yes
1,I am a student who is learning to code,No
2,"I am not primarily a developer, but I write code sometimes as part of my work",Yes
3,I am a developer by profession,No
4,I am a developer by profession,Yes
...,...,...
88878,NaN,Yes
88879,NaN,No
88880,NaN,No
88881,NaN,No
88882,NaN,Yes

In [46]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [47]:
df.loc

In [48]:
df.iloc[0]
#iloc is used to access row by integer location
#values of first row of data frame
#index here is column name

Respondent                                                                                                                  1
MainBranch                                                                             I am a student who is learning to code
Hobbyist                                                                                                                  Yes
OpenSourcer                                                                                                             Never
OpenSource                                                    The quality of OSS and closed source software is about the same
Employment                                                                             Not employed, and not looking for work
Country                                                                                                        United Kingdom
Student                                                                                                                    No
EdLevel                                                                                             Primary/elementary school
UndergradMajor                                                                                                            NaN
EduOther                                    Taught yourself a new language, framework, or tool without taking a formal course
OrgSize                                                                                                                   NaN
DevType                                                                                                                   NaN
YearsCode                                                                                                                   4
Age1stCode                                                                                                                 10
YearsCodePro                                                                                                              NaN
CareerSat                                                                                                                 NaN
JobSat                                                                                                                    NaN
MgrIdiot                                                                                                                  NaN
MgrMoney                                                                                                                  NaN
MgrWant                                                                                                                   NaN
JobSeek                                                                                                                   NaN
LastHireDate                                                                                                              NaN
LastInt                                                                                                                   NaN
FizzBuzz                                                                                                                  NaN
JobFactors                                                                                                                NaN
ResumeUpdate                                                                                                              NaN
CurrencySymbol                                                                                                            NaN
CurrencyDesc                                                                                                              NaN
CompTotal                                                                                                                 NaN
CompFreq                                                                                                                  NaN
ConvertedComp                                                                                                             NaN
WorkWeekHrs                                                                                                               NaN
WorkPlan                                                                                                                  NaN
WorkChallenge                                                                                                             NaN
WorkRemote                                                                                                                NaN
WorkLoc                                                                                                                   NaN
ImpSyn                                                                                                                    NaN
CodeRev                                                                                                                   NaN
CodeRevHrs                                                                                                                NaN
UnitTests                                                                                                                 NaN
PurchaseHow                                                                                                               NaN
PurchaseWhat                                                                                                              NaN
LanguageWorkedWith                                                                            HTML/CSS;Java;JavaScript;Python
LanguageDesireNextYear                                                        C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL
DatabaseWorkedWith                                                                                                     SQLite
DatabaseDesireNextYear                                                                                                  MySQL
PlatformWorkedWith                                                                                              MacOS;Windows
PlatformDesireNextYear                                                                                Android;Arduino;Windows
WebFrameWorkedWith                                                                                               Django;Flask
WebFrameDesireNextYear                                                                                           Flask;jQuery
MiscTechWorkedWith                                                                                                    Node.js
MiscTechDesireNextYear                                                                                                Node.js
DevEnviron                                                                                         IntelliJ;Notepad++;PyCharm
OpSys                                                                                                                 Windows
Containers                                                                                            I do not use containers
BlockchainOrg                                                                                                             NaN
BlockchainIs                                                                                                              NaN
BetterLife                                                                                                                Yes
ITperson                                                                             Fortunately, someone else has that title
OffOn                                                                                                                     Yes
SocialMedia                                                                                                           Twitter
Extraversion                                                                                                           Online
ScreenName                                                                                                           Username
SOVisit1st                                                                                                               2017
SOVisitFreq                                                                                   A few times per month or weekly
SOVisitTo                             Find answers to specific questions;Learn how to do things I didn’t necessarily look for
SOFindAnswer                                                                                               3-5 times per week
SOTimeSaved                                                                                    Stack Overflow was much faster
SOHowMuchTime                                                                                                   31-60 minutes
SOAccount                                                                                                                  No
SOPartFreq                                                                                                                NaN
SOJobs                                                                  No, I didn't know that Stack Overflow had a job board
EntTeams                                                                                  No, and I don't know what those are
SOComm                                                                                                                Neutral
WelcomeChange                                                                         Just as welcome now as I felt last year
SONewContent              Tech articles written by other developers;Industry news about technologies you're interested in;...
Age                                                                                                                        14
Gender                                                                                                                    Man
Trans                                                                                                                      No
Sexuality                                                                                             Straight / Heterosexual
Ethnicity                                                                                                                 NaN
Dependents                                                                                                                 No
SurveyLength                                                                                            Appropriate in length
SurveyEase                                                                                         Neither easy nor difficult
Name: 0, dtype: object

In [49]:
df.iloc[0:3]
#First 3 rows of data frame
#Here in iLoc the end index is exclusive
#But in loc the "end Label" is inclusive because it is label base indexing not location based indexing

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software is about the same,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or tool without taking a formal course",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a job board","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software is about the same,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",NaN,Taken an online course in programming or software development (e.g. a MOOC),NaN,"Developer, desktop or enterprise applications;Developer, front-end",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the company or organization;Specific department or te...,"Something else changed (education, award, media, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change many aspects of our lives,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Designer;Developer, back-end;Developer, front-end;Developer, full-stack",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new opportunities",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies I'd be working with;Remote work options;Flex time ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what seems most important or urgent,Distracting work environment;Inadequate access to necessary tools;Lack of support from management,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult

In [50]:
df.iloc[[0,1],[2,3]]
#1st argument is list of row index and 2nd argument is list of column index

  Hobbyist              OpenSourcer
0      Yes                    Never
1       No  Less than once per year

In [51]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software is about the same,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or tool without taking a formal course",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a job board","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software is about the same,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",NaN,Taken an online course in programming or software development (e.g. a MOOC),NaN,"Developer, desktop or enterprise applications;Developer, front-end",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the company or organization;Specific department or te...,"Something else changed (education, award, media, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change many aspects of our lives,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Designer;Developer, back-end;Developer, front-end;Developer, full-stack",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new opportunities",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies I'd be working with;Remote work options;Flex time ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what seems most important or urgent,Distracting work environment;Inadequate access to necessary tools;Lack of support from management,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software is about the same,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job ...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Interview with people in senior / management roles",No,"Languages, frameworks, and other technologies I'd be working with;Office environment or company ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what seems most important or urgent,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence on purchasing new technology,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the time / relax,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job ...,"10,000 or more employees","Academic researcher;Developer, desktop or enterprise applications;Developer, full-stack;Develope...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a whiteboard);Solve a brain-teaser style puzzle;Inte...",No,"Industry that I'd be working in;Languages, frameworks, and other technologies I'd be working wit...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",Being tasked with non-development work;Inadequate access to necessary tools;Non-work commitments...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [ ]:

df.loc[0:2,'MainBranch':'Hobbyist']
#slicing is inclusive in loc because it is label based indexing
# searching by label of row and column
#rows do not have lable so default lable is 0,1,2,..
#column do have lable so we can use column name to access the data

,MainBranch,Hobbyist
0,I am a student who is learning to code,Yes
1,I am a student who is learning to code,No
2,"I am not primarily a developer, but I write code sometimes as part of my work",Yes

In [53]:
df.shape

(88883, 85)

In [54]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [55]:
df['Hobbyist'].value_counts()
#Gives count of each unique value in the column

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [56]:
df.loc[0]

Respondent                                                                                                                  1
MainBranch                                                                             I am a student who is learning to code
Hobbyist                                                                                                                  Yes
OpenSourcer                                                                                                             Never
OpenSource                                                    The quality of OSS and closed source software is about the same
Employment                                                                             Not employed, and not looking for work
Country                                                                                                        United Kingdom
Student                                                                                                                    No
EdLevel                                                                                             Primary/elementary school
UndergradMajor                                                                                                            NaN
EduOther                                    Taught yourself a new language, framework, or tool without taking a formal course
OrgSize                                                                                                                   NaN
DevType                                                                                                                   NaN
YearsCode                                                                                                                   4
Age1stCode                                                                                                                 10
YearsCodePro                                                                                                              NaN
CareerSat                                                                                                                 NaN
JobSat                                                                                                                    NaN
MgrIdiot                                                                                                                  NaN
MgrMoney                                                                                                                  NaN
MgrWant                                                                                                                   NaN
JobSeek                                                                                                                   NaN
LastHireDate                                                                                                              NaN
LastInt                                                                                                                   NaN
FizzBuzz                                                                                                                  NaN
JobFactors                                                                                                                NaN
ResumeUpdate                                                                                                              NaN
CurrencySymbol                                                                                                            NaN
CurrencyDesc                                                                                                              NaN
CompTotal                                                                                                                 NaN
CompFreq                                                                                                                  NaN
ConvertedComp                                                                                                             NaN
WorkWeekHrs                                                                                                               NaN
WorkPlan                                                                                                                  NaN
WorkChallenge                                                                                                             NaN
WorkRemote                                                                                                                NaN
WorkLoc                                                                                                                   NaN
ImpSyn                                                                                                                    NaN
CodeRev                                                                                                                   NaN
CodeRevHrs                                                                                                                NaN
UnitTests                                                                                                                 NaN
PurchaseHow                                                                                                               NaN
PurchaseWhat                                                                                                              NaN
LanguageWorkedWith                                                                            HTML/CSS;Java;JavaScript;Python
LanguageDesireNextYear                                                        C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL
DatabaseWorkedWith                                                                                                     SQLite
DatabaseDesireNextYear                                                                                                  MySQL
PlatformWorkedWith                                                                                              MacOS;Windows
PlatformDesireNextYear                                                                                Android;Arduino;Windows
WebFrameWorkedWith                                                                                               Django;Flask
WebFrameDesireNextYear                                                                                           Flask;jQuery
MiscTechWorkedWith                                                                                                    Node.js
MiscTechDesireNextYear                                                                                                Node.js
DevEnviron                                                                                         IntelliJ;Notepad++;PyCharm
OpSys                                                                                                                 Windows
Containers                                                                                            I do not use containers
BlockchainOrg                                                                                                             NaN
BlockchainIs                                                                                                              NaN
BetterLife                                                                                                                Yes
ITperson                                                                             Fortunately, someone else has that title
OffOn                                                                                                                     Yes
SocialMedia                                                                                                           Twitter
Extraversion                                                                                                           Online
ScreenName                                                                                                           Username
SOVisit1st                                                                                                               2017
SOVisitFreq                                                                                   A few times per month or weekly
SOVisitTo                             Find answers to specific questions;Learn how to do things I didn’t necessarily look for
SOFindAnswer                                                                                               3-5 times per week
SOTimeSaved                                                                                    Stack Overflow was much faster
SOHowMuchTime                                                                                                   31-60 minutes
SOAccount                                                                                                                  No
SOPartFreq                                                                                                                NaN
SOJobs                                                                  No, I didn't know that Stack Overflow had a job board
EntTeams                                                                                  No, and I don't know what those are
SOComm                                                                                                                Neutral
WelcomeChange                                                                         Just as welcome now as I felt last year
SONewContent              Tech articles written by other developers;Industry news about technologies you're interested in;...
Age                                                                                                                        14
Gender                                                                                                                    Man
Trans                                                                                                                      No
Sexuality                                                                                             Straight / Heterosexual
Ethnicity                                                                                                                 NaN
Dependents                                                                                                                 No
SurveyLength                                                                                            Appropriate in length
SurveyEase                                                                                         Neither easy nor difficult
Name: 0, dtype: object

In [57]:
df.loc[0,'Hobbyist']

'Yes'

In [58]:
df.loc[[0,1,2],'Hobbyist']

0    Yes
1     No
2    Yes
Name: Hobbyist, dtype: object

In [59]:
df.loc[0:5,'Hobbyist':'Employment']
#last value i.e. 5 above is inclusive
#employement also inclusive

,Hobbyist,OpenSourcer,OpenSource,Employment
0,Yes,Never,The quality of OSS and closed source software is about the same,"Not employed, and not looking for work"
1,No,Less than once per year,The quality of OSS and closed source software is about the same,"Not employed, but looking for work"
2,Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time
3,No,Never,The quality of OSS and closed source software is about the same,Employed full-time
4,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time
5,Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time