In [21]:
import pandas as pd
df = pd.read_csv('./Data_2019/survey_results_public.csv')
schema_df = pd.read_csv('./Data_2019/survey_results_schema.csv')
pd.set_option('display.max_columns', 85) #to display all columns in the dataframe
pd.set_option('display.max_rows', 85)   #to see all rows in the dataframe of schema

In [22]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [23]:
people = {
    "first": ["Corey", "Jane", "John"],
    "last": ["Schafer", "Doe", "Smith"],
    "email": ["Corey.Schafer@gmail.com", "Jane.Doe@gmail.com", "John.Smith@gmail.com"]
}
df1 = pd.DataFrame(people)

In [24]:
df1.columns

Index(['first', 'last', 'email'], dtype='object')

In [25]:
df1.columns = ["first_name", "last_name", "email"]
df1.columns

Index(['first_name', 'last_name', 'email'], dtype='object')

In [26]:
df1.columns = [x.upper() for x in df1.columns]
df1.columns

Index(['FIRST_NAME', 'LAST_NAME', 'EMAIL'], dtype='object')

In [27]:
df1.columns = df1.columns.str.replace("_", " ")
df1.columns

Index(['FIRST NAME', 'LAST NAME', 'EMAIL'], dtype='object')

In [28]:
df1.columns = df1.columns.str.replace(" ", "_")
df1.columns

Index(['FIRST_NAME', 'LAST_NAME', 'EMAIL'], dtype='object')

In [29]:
df1.columns = [ x.lower() for x in df1.columns]
df1.columns

Index(['first_name', 'last_name', 'email'], dtype='object')

In [30]:
df1.rename(columns={"first_name": "first", "last_name": "last", "email": "email_address"},inplace=True)
df1.columns

Index(['first', 'last', 'email_address'], dtype='object')

In [31]:
df1

   first     last            email_address
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John    Smith     John.Smith@gmail.com

In [32]:
df1.loc[2] #Display the row with index 2 (C-Based Indexing)

first                            John
last                            Smith
email_address    John.Smith@gmail.com
Name: 2, dtype: object

In [33]:
df1.loc[2,['last','email_address']] = ['Doe', 'John.Doe@gmail.com']
df1.loc[2]

first                          John
last                            Doe
email_address    John.Doe@gmail.com
Name: 2, dtype: object

In [34]:
df1.loc[2,'last'] = 'Smith'
df1.loc[2]

first                          John
last                          Smith
email_address    John.Doe@gmail.com
Name: 2, dtype: object

In [35]:
df1.at[2,'last'] = 'Doe'
df1.loc[2]

first                          John
last                            Doe
email_address    John.Doe@gmail.com
Name: 2, dtype: object

In [36]:
filt = df1['email_address'] == 'John.Doe@gmail.com'
df1.loc[filt]

  first last       email_address
2  John  Doe  John.Doe@gmail.com

In [37]:
df1.loc[filt,'last']

2    Doe
Name: last, dtype: object

In [38]:
df1[filt]['last'] = 'Smith' #This will not update the value in the dataframe because we are creating a copy of the dataframe and updating the value in the copy. We need to use loc to update the value in the original dataframe.

<ipython-input-38-de258d8a5e25>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[filt]['last'] = 'Smith' #This will not update the value in the dataframe because we are creating a copy of the dataframe and updating the value in the copy. We need to use loc to update the value in the original dataframe.

In [39]:
df1.loc[filt,'last'] = 'Smith'

In [40]:
df1

   first     last            email_address
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John    Smith       John.Doe@gmail.com

In [41]:
df1['email_address'] = df1['email_address'].str.lower() #several rows ar once
df1
#df1['email_address'] basically gives us a series
#df1['email_address'].str will give us access to the string methods for that series

   first     last            email_address
0  Corey  Schafer  corey.schafer@gmail.com
1   Jane      Doe       jane.doe@gmail.com
2   John    Smith       john.doe@gmail.com

In [42]:
df1.columns

Index(['first', 'last', 'email_address'], dtype='object')

In [43]:
df1.rename(columns={'email_address': 'email'}, inplace=True)
df1.columns
#In pandas, the primary difference is what they modify: 
# rename() targets axis labels (column names and row indices), 
# while replace() targets the actual data values within the DataFrame.

Index(['first', 'last', 'email'], dtype='object')

In [44]:
df1

   first     last                    email
0  Corey  Schafer  corey.schafer@gmail.com
1   Jane      Doe       jane.doe@gmail.com
2   John    Smith       john.doe@gmail.com

In [ ]:
#Four Methods to Update Rows and Columns in a DataFrame:
#apply
#map
#applymap
#replace

In [52]:
df1.loc[:,'email']

0    corey.schafer@gmail.com
1         jane.doe@gmail.com
2         john.doe@gmail.com
Name: email, dtype: object

In [ ]:
#Pandas uses the object dtype for storing strings.

In [53]:
df1['email']

0    corey.schafer@gmail.com
1         jane.doe@gmail.com
2         john.doe@gmail.com
Name: email, dtype: object

In [ ]:
#df1.loc[:,'email'].str.len()
df1['email'].str.len()

#Both above statements will give us the same result. 
# The first one is using loc to select the column and then applying the string method to it. The second one is directly applying the string method to the column.

0    23
1    18
2    18
Name: email, dtype: int64

In [55]:
df1['email'].apply(len)

0    23
1    18
2    18
Name: email, dtype: int64

In [59]:
df1['email']

0    COREY.SCHAFER@GMAIL.COM
1         JANE.DOE@GMAIL.COM
2         JOHN.DOE@GMAIL.COM
Name: email, dtype: object

In [ ]:
def make_uppercase(string):
    return string.upper()

df1['email'] = [make_uppercase(x) for x in df1['email']] 
df1['email']

0    COREY.SCHAFER@GMAIL.COM
1         JANE.DOE@GMAIL.COM
2         JOHN.DOE@GMAIL.COM
Name: email, dtype: object

In [ ]:
def update_email(email):
    return email.lower()

#df1['email'].apply(update_email) 
# this will return a new series
#  but will not update the original dataframe. 
# We need to assign it back to the original dataframe
#  to update it.
df1['email'] = df1['email'].apply(update_email)
df1['email']

0    corey.schafer@gmail.com
1         jane.doe@gmail.com
2         john.doe@gmail.com
Name: email, dtype: object

In [ ]:
#Lamda Functions
df1['email'] = df1['email'].apply(lambda x: x.upper())
df1['email']

#Lambda functions (or anonymous functions) are best 
# used for short, single-use, and simple operations 
# where defining a named function (def) would be 
# overkill. They are ideal as arguments to higher-order
#  functions—like map(), filter(), or sorted()—or 
# for creating small, disposable logic to be used once.


#Filtering a list in Python: 
#filtered = list(filter(lambda x: x % 2 == 0, numbers))
#Sorting with a key in Python: 
#data.sort(key=lambda x: x.name)
#Simple operations in C++: 
#auto add = [](int a, int b) { return a + b; };

0    COREY.SCHAFER@GMAIL.COM
1         JANE.DOE@GMAIL.COM
2         JOHN.DOE@GMAIL.COM
Name: email, dtype: object

In [ ]:
df1.apply(len)
# Not Applying len function to entire dataframe
# but to each column (series) in the dataframe

first    3
last     3
email    3
dtype: int64

In [ ]:
df1.apply(len,axis = 'columns')
#axis = 'rows' is the default value for axis parameter in apply method.
#Basically Couting the number of columns in each row

0    3
1    3
2    3
dtype: int64

In [ ]:
df1.apply(pd.Series.min)
#In each Column find the minimum value.

first                      Corey
last                         Doe
email    COREY.SCHAFER@GMAIL.COM
dtype: object

In [ ]:
df1.apply(lambda x: x.min())
#lamda working on series object and finding the minimum value in each column.

first                      Corey
last                         Doe
email    COREY.SCHAFER@GMAIL.COM
dtype: object

In [69]:
#applymap is used to apply a function 
# to each element of the dataframe.

df1.applymap(len)

   first  last  email
0      5     7     23
1      4     3     18
2      4     5     18

In [ ]:
 #1. df1.applymap(lambda x: x.lower())

#2. df1.applymap(str.lower)

#above 2 are same this str.lower will also work 
# because it is a string method and 
# applymap will apply it to each element 
# in the dataframe.
#however it will not work if there 
# are any non-string values in the dataframe.
#in that case we can use a lambda function to check 
#if the value is a string before applying the lower method.
#something like below
df1.applymap(lambda x: x.lower() if isinstance(x, str) else x)

   first     last                    email
0  corey  schafer  corey.schafer@gmail.com
1   jane      doe       jane.doe@gmail.com
2   john    smith       john.doe@gmail.com

In [71]:
df1

   first     last                    email
0  Corey  Schafer  COREY.SCHAFER@GMAIL.COM
1   Jane      Doe       JANE.DOE@GMAIL.COM
2   John    Smith       JOHN.DOE@GMAIL.COM

In [ ]:
#map is used to substitute each value in a Series with another value,
# that may be derived from a function, a dictionary, or a Series.

#df1['first'] is a series object and 
# we can use map method on it to 
# replace the values in the series 
# with the values in the dictionary.

df1['first'].map({'Corey': 'Chris', 'Jane': 'Mary'})
#This will replace 'Corey' with 'Chris' 
# and 'Jane' with 'Mary in the 'first' 
# column of the dataframe pd1. 
#The values that are not in the dictionary 
# will be replaced with NaN.

0    Chris
1     Mary
2      NaN
Name: first, dtype: object

In [ ]:
#If we want to keep the values that are not in the dictionary
# then replace method is used instead of map method.
df1['first'].replace({'Corey': 'Chris', 'Jane': 'Mary'})
#This will replace 'Corey' with 'Chris'
# and 'Jane' with 'Mary in the 'first'
#df1['first'] = df1['first'].replace({'Corey': 'Chris', 'Jane': 'Mary'})
# this will update the values in the dataframe because 
# we are assigning the result back to the original dataframe.

0    Chris
1     Mary
2     John
Name: first, dtype: object

In [78]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [81]:
df.rename(columns ={'ConvertedComp':'SalaryUSD'},inplace=True)

In [82]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [83]:
df['SalaryUSD']

0            NaN
1            NaN
2         8820.0
3        61000.0
4            NaN
          ...
88878        NaN
88879        NaN
88880        NaN
88881        NaN
88882        NaN
Name: SalaryUSD, Length: 88883, dtype: float64

In [84]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [85]:
df['Hobbyist'].map({'Yes': True, 'No': False})

0         True
1        False
2         True
3        False
4         True
         ...
88878     True
88879    False
88880    False
88881    False
88882     True
Name: Hobbyist, Length: 88883, dtype: bool

In [ ]:
df['Hobbyist'] = df['Hobbyist'].map({'Yes': True, 'No': False})
df['Hobbyist']

#For any other value than True And False Map will return NaN
# If you want to avoid that you can use replace method instead of map method.

0         True
1        False
2         True
3        False
4         True
         ...
88878     True
88879    False
88880    False
88881    False
88882     True
Name: Hobbyist, Length: 88883, dtype: bool